'use client';

import React from 'react';
import * as XLSX from 'xlsx-js-style';
import { useSession } from 'next-auth/react';

interface ReportRiskSummaryProps {
    isOpen: boolean;
    onClose: () => void;
    data: any[];
    loading: boolean;
}

const ReportRiskSummary: React.FC<ReportRiskSummaryProps> = ({ isOpen, onClose, data, loading }) => {
    const { data: session } = useSession();

    if (!isOpen) return null;

    // Debug: Log data to check COLOR field
    console.log('=== ReportRiskSummary Data ===');
    console.log('Total rows:', data.length);
    if (data.length > 0) {
        console.log('Sample row:', data[0]);
        console.log('All COLOR values:', data.map((row, idx) => ({
            index: idx,
            RISK_DESC: row.RISK_DESC,
            COLOR: row.COLOR,
            hasColor: !!row.COLOR
        })));
    }

    // Get current user name from session
    const getUserName = () => {
        return session?.user?.name || session?.user?.email || 'System User';
    };

    // Handle Excel export
    const handleExportToExcel = () => {
        // Get current date and time
        const now = new Date();
        const dateTimeStr = now.toISOString().replace('T', ' ').substring(0, 19);
        const userName = getUserName();

        // Prepare data for Excel with title and footer
        const excelData = data.map(row => ({
            'Owner Name': row.OWNER_NAME || '',
            'Parent Name': row.PARENT_NAME || '',
            'Asset Name': row.ASSET_NAME || '',
            'POF Level': row.POF_LEVEL || '',
            'COF Level': row.COF_LEVEL || '',
            'Damage COF': row.DAMAGE_COF || '',
            'Health COF': row.HEALTH_COF || '',
            'Risk Desc': row.RISK_DESC || ''
        }));

        // Create worksheet with empty data first to manually control layout
        const ws = XLSX.utils.aoa_to_sheet([]);

        // Row 1: Title
        XLSX.utils.sheet_add_aoa(ws, [['Risk Summary Report']], { origin: 'A1' });

        // Row 2: Empty row

        // Row 3: Headers
        const headers = ['Owner Name', 'Parent Name', 'Asset Name', 'POF Level', 'COF Level', 'Damage COF', 'Health COF', 'Risk Desc'];
        XLSX.utils.sheet_add_aoa(ws, [headers], { origin: 'A3' });

        // Row 4+: Data
        const dataRows = data.map(row => [
            row.OWNER_NAME || '',
            row.PARENT_NAME || '',
            row.ASSET_NAME || '',
            row.POF_LEVEL || '',
            row.COF_LEVEL || '',
            row.DAMAGE_COF || '',
            row.HEALTH_COF || '',
            row.RISK_DESC || ''
        ]);
        XLSX.utils.sheet_add_aoa(ws, dataRows, { origin: 'A4' });

        // Footer rows (after data)
        const footerStartRow = 4 + data.length + 1; // +1 for empty rows
        const footerText = `Report generated by ${userName} on ${dateTimeStr}`;
        XLSX.utils.sheet_add_aoa(ws, [[footerText]], { origin: `A${footerStartRow}` });

        // Apply cell styles with colors
        const range = XLSX.utils.decode_range(ws['!ref'] || 'A1');

        // Define border style
        const borderStyle = {
            top: { style: 'thin', color: { rgb: '000000' } },
            bottom: { style: 'thin', color: { rgb: '000000' } },
            left: { style: 'thin', color: { rgb: '000000' } },
            right: { style: 'thin', color: { rgb: '000000' } }
        };

        // Style the title (Row 1) - Bold, large, centered
        const titleCell = ws['A1'];
        if (titleCell) {
            titleCell.s = {
                font: { bold: true, sz: 16, color: { rgb: '000000' } },
                alignment: { horizontal: 'center', vertical: 'center' }
            };
        }

        // Merge title across all columns
        ws['!merges'] = ws['!merges'] || [];
        ws['!merges'].push({ s: { r: 0, c: 0 }, e: { r: 0, c: 7 } }); // Merge A1:H1

        // Style the header row (Row 3) - bold with gray background and borders
        for (let col = 0; col < 8; col++) {
            const cellAddress = XLSX.utils.encode_cell({ r: 2, c: col }); // Row 3 (index 2)
            if (!ws[cellAddress]) continue;
            ws[cellAddress].s = {
                font: { bold: true, color: { rgb: '000000' } },
                fill: { fgColor: { rgb: 'D3D3D3' } },
                alignment: { horizontal: 'center', vertical: 'center' },
                border: borderStyle
            };
        }

        // Apply styles to all data cells (starting from Row 4)
        for (let row = 0; row < data.length; row++) {
            for (let col = 0; col < 8; col++) {
                const cellAddress = XLSX.utils.encode_cell({ r: row + 3, c: col }); // Data starts at row 4 (index 3)
                if (!ws[cellAddress]) continue;

                // Base style with borders
                const baseStyle = {
                    alignment: { horizontal: 'left', vertical: 'center' },
                    border: borderStyle
                };

                // Apply special styling to Risk Desc column (column H, index 7)
                if (col === 7) {
                    const dataRow = data[row];
                    if (dataRow && dataRow.COLOR) {
                        ws[cellAddress].s = {
                            ...baseStyle,
                            fill: { fgColor: { rgb: dataRow.COLOR } },
                            font: { bold: true, color: { rgb: '000000' } }
                        };
                    } else {
                        ws[cellAddress].s = baseStyle;
                    }
                } else {
                    ws[cellAddress].s = baseStyle;
                }
            }
        }

        // Style the footer (italic, gray)
        const footerRowNumber = 4 + data.length + 1;
        const footerCell = ws[`A${footerRowNumber}`];
        if (footerCell) {
            footerCell.s = {
                font: { italic: true, color: { rgb: '666666' } },
                alignment: { horizontal: 'left', vertical: 'center' }
            };
        }

        // Merge footer across all columns
        ws['!merges'].push({ s: { r: footerRowNumber - 1, c: 0 }, e: { r: footerRowNumber - 1, c: 7 } });

        // Set column widths
        ws['!cols'] = [
            { wch: 20 }, // Owner Name
            { wch: 20 }, // Parent Name
            { wch: 30 }, // Asset Name
            { wch: 12 }, // POF Level
            { wch: 12 }, // COF Level
            { wch: 12 }, // Damage COF
            { wch: 12 }, // Health COF
            { wch: 15 }  // Risk Desc
        ];

        // Create workbook and add worksheet
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'Risk Summary');

        // Generate and download file
        XLSX.writeFile(wb, `risk_summary_report_${new Date().toISOString().slice(0, 10)}.xlsx`);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50" onClick={onClose}>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-[95vw] w-full mx-4 max-h-[90vh] overflow-hidden" onClick={(e) => e.stopPropagation()}>
                {/* Modal Header */}
                <div className="flex items-center justify-between p-5 border-b border-gray-200 dark:border-gray-700">
                    <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
                        Risk Summary Report
                    </h3>
                    <button
                        onClick={onClose}
                        className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
                    >
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                {/* Modal Body */}
                <div className="p-5 overflow-auto max-h-[calc(90vh-140px)]">
                    {loading ? (
                        <div className="flex items-center justify-center py-12">
                            <div className="text-center">
                                <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
                                <p className="mt-4 text-gray-600 dark:text-gray-400">Loading risk summary...</p>
                            </div>
                        </div>
                    ) : data.length === 0 ? (
                        <div className="flex items-center justify-center py-12">
                            <p className="text-gray-500 dark:text-gray-400">No risk summary data available</p>
                        </div>
                    ) : (
                        <div className="overflow-x-auto">
                            <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                                <thead className="bg-gray-50 dark:bg-gray-900">
                                    <tr>
                                        {/* <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Hierarchy ID</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Asset ID</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">RBIM ID</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Level</th> */}
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Owner Name</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Parent Name</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Asset Name</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">POF Level</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">COF Level</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Damage COF</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Health COF</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Risk Desc</th>
                                        {/* <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Color</th> */}
                                    </tr>
                                </thead>
                                <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                                    {data.map((row, index) => {
                                        // Debug: Log each row's color
                                        if (index < 3) { // Only log first 3 rows to avoid spam
                                            console.log(`Row ${index} - RISK_DESC: ${row.RISK_DESC}, COLOR: ${row.COLOR}, type: ${typeof row.COLOR}`);
                                        }
                                        return (
                                        <tr key={index} className="hover:bg-gray-50 dark:hover:bg-gray-700">
                                            {/* <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.HIRARKI_ID || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.assetID || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.rbimID || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.LEVEL || '-'}</td> */}
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.OWNER_NAME || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.PARENT_NAME || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.ASSET_NAME || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.POF_LEVEL || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.COF_LEVEL || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.DAMAGE_COF || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.HEALTH_COF || '-'}</td>
                                            <td
                                                className="px-4 py-3 text-sm font-semibold"
                                                style={{
                                                    backgroundColor: row.COLOR ? `#${row.COLOR}` : 'transparent',
                                                    color: row.COLOR ? '#000000' : undefined,
                                                }}
                                            >
                                                {row.RISK_DESC || '-'}
                                            </td>
                                            {/* <td className="px-4 py-3 text-sm">
                                                {row.COLOR ? (
                                                    <span
                                                        className="inline-block px-3 py-1 rounded-full text-xs font-semibold"
                                                        style={{
                                                            backgroundColor: row.COLOR,
                                                            color: '#fff',
                                                        }}
                                                    >
                                                        {row.COLOR}
                                                    </span>
                                                ) : (
                                                    '-'
                                                )}
                                            </td> */}
                                        </tr>
                                        );
                                    })}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>

                {/* Modal Footer */}
                <div className="flex items-center justify-end gap-3 p-5 border-t border-gray-200 dark:border-gray-700">
                    <button
                        onClick={handleExportToExcel}
                        className="btn btn-primary"
                        disabled={loading || data.length === 0}
                    >
                        Save
                    </button>
                    <button
                        onClick={onClose}
                        className="btn btn-outline-danger"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
};

export default ReportRiskSummary;
