'use client';

import React from 'react';
import * as XLSX from 'xlsx-js-style';
import { useSession } from 'next-auth/react';

interface Report101Props {
    isOpen: boolean;
    onClose: () => void;
    data: any[];
    loading: boolean;
    reportTitle?: string;
}

const Report101: React.FC<Report101Props> = ({ isOpen, onClose, data, loading, reportTitle }) => {
    const { data: session } = useSession();

    if (!isOpen) return null;

    const getUserName = () => {
        return session?.user?.name || session?.user?.email || 'System User';
    };

    // Handle Excel export
    const handleExportToExcel = () => {
        const now = new Date();
        const dateTimeStr = now.toISOString().replace('T', ' ').substring(0, 19);
        const userName = getUserName();
        const title = reportTitle || 'Report 10-1';

        // Calculate year range: from min YEAR_OF_ANALYSIS to max INSP_YEAR
        const yearOfAnalysisList = data.map(row => Number(row.YEAR_OF_ANALYSIS)).filter(y => !isNaN(y) && y > 0);
        const inspYearList = data.map(row => Number(row.INSP_YEAR)).filter(y => !isNaN(y) && y > 0);

        const minYear = yearOfAnalysisList.length > 0 ? Math.min(...yearOfAnalysisList) : new Date().getFullYear();
        const maxYear = inspYearList.length > 0 ? Math.max(...inspYearList) : minYear;

        // Generate array of years from minYear to maxYear
        const yearColumns = [];
        for (let year = minYear; year <= maxYear; year++) {
            yearColumns.push(year);
        }

        const ws = XLSX.utils.aoa_to_sheet([]);

        // Row 1: Title
        XLSX.utils.sheet_add_aoa(ws, [[title]], { origin: 'A1' });

        // Row 2: Empty row

        // Row 3: Headers
        const baseHeaders = ['No.', 'Unit Name', 'Asset Name', 'Description', 'Risk Level', 'Damage Type', 'TMSF Value', 'Intrusive', 'Inspection Technique', 'Inspection Description', 'Inspection Effectiveness', 'Date of Last', 'Inspection Year', 'Year of Analysis'];
        const headers = [...baseHeaders, ...yearColumns.map(y => y.toString()), 'Remarks'];
        XLSX.utils.sheet_add_aoa(ws, [headers], { origin: 'A3' });

        // Row 4+: Data - Group by Unit Name, Asset Name, Description, and Risk Level
        const dataRows = data.map((row, index) => {
            // Check if this is the first row or if any grouped field is different from previous row
            const showGrouped = index === 0 ||
                data[index - 1].UNIT_NAME !== row.UNIT_NAME ||
                data[index - 1].ASSET_NAME !== row.ASSET_NAME ||
                data[index - 1].DESCRIPTION !== row.DESCRIPTION ||
                data[index - 1].RISK_LEVEL !== row.RISK_LEVEL;
            const rowNumber = showGrouped ? (data.slice(0, index).filter((r, i) =>
                i === 0 ||
                data[i - 1].UNIT_NAME !== r.UNIT_NAME ||
                data[i - 1].ASSET_NAME !== r.ASSET_NAME ||
                data[i - 1].DESCRIPTION !== r.DESCRIPTION ||
                data[i - 1].RISK_LEVEL !== r.RISK_LEVEL
            ).length + 1) : '';

            // Format TMSF_VALUE: 2 decimals, blank if zero
            const tmsfValue = row.TMSF_VALUE != null && Number(row.TMSF_VALUE) !== 0
                ? Number(row.TMSF_VALUE)
                : '';

            // Generate year column values with "X" marks
            const yearValues = yearColumns.map(year => {
                return Number(row.INSP_YEAR) === year ? 'X' : '';
            });

            return [
                rowNumber,
                showGrouped ? (row.UNIT_NAME || '') : '',
                showGrouped ? (row.ASSET_NAME || '') : '',
                showGrouped ? (row.DESCRIPTION || '') : '',
                showGrouped ? (row.RISK_LEVEL || '') : '',
                row.DAMAGE_TYPE || '',
                tmsfValue,
                row.INSTRUSIVE || '',
                row.INSP_TECH || '',
                row.INSP_DESC || '',
                row.INSP_EFFECT || '',
                row.DATE_OF_LAST || '',
                row.INSP_YEAR || '',
                row.YEAR_OF_ANALYSIS || '',
                ...yearValues,
                row.REMARKS || ''
            ];
        });
        XLSX.utils.sheet_add_aoa(ws, dataRows, { origin: 'A4' });

        // Footer rows (after data)
        const footerStartRow = 4 + data.length + 1; // +1 for empty row
        const footerText = `Report generated by ${userName} on ${dateTimeStr}`;
        XLSX.utils.sheet_add_aoa(ws, [[footerText]], { origin: `A${footerStartRow}` });

        // Apply cell styles with colors
        const range = XLSX.utils.decode_range(ws['!ref'] || 'A1');

        // Define border style
        const borderStyle = {
            top: { style: 'thin', color: { rgb: '000000' } },
            bottom: { style: 'thin', color: { rgb: '000000' } },
            left: { style: 'thin', color: { rgb: '000000' } },
            right: { style: 'thin', color: { rgb: '000000' } }
        };

        // Style the title (Row 1) - Bold, large, centered
        const titleCell = ws['A1'];
        if (titleCell) {
            titleCell.s = {
                font: { bold: true, sz: 16, color: { rgb: '000000' } },
                alignment: { horizontal: 'center', vertical: 'center' }
            };
        }

        // Calculate total number of columns (base headers + year columns + Remarks)
        const totalColumns = headers.length;

        // Merge title across all columns
        ws['!merges'] = ws['!merges'] || [];
        ws['!merges'].push({ s: { r: 0, c: 0 }, e: { r: 0, c: totalColumns - 1 } });

        // Style the header row (Row 3) - bold with gray background and borders
        for (let col = 0; col < totalColumns; col++) {
            const cellAddress = XLSX.utils.encode_cell({ r: 2, c: col }); // Row 3 (index 2)
            if (!ws[cellAddress]) continue;
            ws[cellAddress].s = {
                font: { bold: true, color: { rgb: '000000' } },
                fill: { fgColor: { rgb: 'D3D3D3' } },
                alignment: { horizontal: 'center', vertical: 'center' },
                border: borderStyle
            };
        }

        // Apply styles to all data cells (starting from Row 4)
        // Year columns start at index 14 (after Year of Analysis)
        const yearColumnStartIndex = 14;
        const remarksColumnIndex = yearColumnStartIndex + yearColumns.length;

        for (let row = 0; row < data.length; row++) {
            for (let col = 0; col < totalColumns; col++) {
                const cellAddress = XLSX.utils.encode_cell({ r: row + 3, c: col }); // Data starts at row 4 (index 3)
                if (!ws[cellAddress]) continue;

                // Base style with borders
                const baseStyle: any = {
                    alignment: { horizontal: col === 0 ? 'center' : 'left', vertical: 'center' },
                    border: borderStyle
                };

                // Center align year columns (X marks)
                if (col >= yearColumnStartIndex && col < remarksColumnIndex) {
                    baseStyle.alignment.horizontal = 'center';
                }

                // Add background color based on COLOR for Risk Level column (col 4)
                // Only apply color when the cell has a value (not blank due to grouping)
                if (col === 4 && data[row].COLOR && ws[cellAddress].v) {
                    baseStyle.fill = { fgColor: { rgb: data[row].COLOR.replace('#', '') } };
                }

                // Add number format with 2 decimals for TMSF Value (col 6)
                if (col === 6) {
                    baseStyle.numFmt = '0.00';
                }

                ws[cellAddress].s = baseStyle;
            }
        }

        // Style the footer (italic, gray)
        const footerRowNumber = footerStartRow;
        const footerCell = ws[`A${footerRowNumber}`];
        if (footerCell) {
            footerCell.s = {
                font: { italic: true, color: { rgb: '666666' } },
                alignment: { horizontal: 'left', vertical: 'center' }
            };
        }

        // Merge footer across all columns
        ws['!merges'].push({ s: { r: footerRowNumber - 1, c: 0 }, e: { r: footerRowNumber - 1, c: totalColumns - 1 } });

        // Set column widths - base columns + year columns + remarks
        const baseColWidths = [
            { wch: 8 },  // No.
            { wch: 20 }, // Unit Name
            { wch: 25 }, // Asset Name
            { wch: 30 }, // Description
            { wch: 12 }, // Risk Level
            { wch: 20 }, // Damage Type
            { wch: 12 }, // TMSF Value
            { wch: 12 }, // Intrusive
            { wch: 25 }, // Inspection Technique
            { wch: 30 }, // Inspection Description
            { wch: 20 }, // Inspection Effectiveness
            { wch: 15 }, // Date of Last
            { wch: 15 }, // Inspection Year
            { wch: 15 }, // Year of Analysis
        ];
        const yearColWidths = yearColumns.map(() => ({ wch: 8 })); // Year columns
        const remarksColWidth = [{ wch: 30 }]; // Remarks

        ws['!cols'] = [...baseColWidths, ...yearColWidths, ...remarksColWidth];

        // Create workbook and add worksheet
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'Report 10-1');

        // Generate and download file
        XLSX.writeFile(wb, `report_10_1_${new Date().toISOString().slice(0, 10)}.xlsx`);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50" onClick={onClose}>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-[95vw] w-full mx-4 max-h-[90vh] overflow-hidden" onClick={(e) => e.stopPropagation()}>
                {/* Modal Header */}
                <div className="flex items-center justify-between p-5 border-b border-gray-200 dark:border-gray-700">
                    <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
                        {reportTitle || 'Report 10-1'}
                    </h3>
                    <button
                        onClick={onClose}
                        className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
                    >
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                {/* Modal Body */}
                <div className="overflow-auto max-h-[calc(90vh-140px)]">
                    {loading ? (
                        <div className="flex items-center justify-center py-12">
                            <div className="text-center">
                                <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
                                <p className="mt-4 text-gray-600 dark:text-gray-400">Loading report...</p>
                            </div>
                        </div>
                    ) : data.length === 0 ? (
                        <div className="flex items-center justify-center py-12">
                            <p className="text-gray-500 dark:text-gray-400">No data available</p>
                        </div>
                    ) : (
                        <div className="p-5">
                            {(() => {
                                // Calculate year range for HTML table
                                const yearOfAnalysisList = data.map(row => Number(row.YEAR_OF_ANALYSIS)).filter(y => !isNaN(y) && y > 0);
                                const inspYearList = data.map(row => Number(row.INSP_YEAR)).filter(y => !isNaN(y) && y > 0);

                                const minYear = yearOfAnalysisList.length > 0 ? Math.min(...yearOfAnalysisList) : new Date().getFullYear();
                                const maxYear = inspYearList.length > 0 ? Math.max(...inspYearList) : minYear;

                                const yearColumns = [];
                                for (let year = minYear; year <= maxYear; year++) {
                                    yearColumns.push(year);
                                }

                                return (
                                    <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                                        <thead className="bg-gray-50 dark:bg-gray-900">
                                            <tr>
                                                <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">No.</th>
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Unit Name</th>
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Asset Name</th>
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Description</th>
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Risk Level</th>
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Damage Type</th>
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">TMSF Value</th>
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Intrusive</th>
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Inspection Technique</th>
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Inspection Description</th>
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Inspection Effectiveness</th>
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Date of Last</th>
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Inspection Year</th>
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Year of Analysis</th>
                                                {yearColumns.map(year => (
                                                    <th key={year} className="px-4 py-3 text-center text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">{year}</th>
                                                ))}
                                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Remarks</th>
                                            </tr>
                                        </thead>
                                <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                                    {data.map((row, index) => {
                                        // Check if this is the first row or if any grouped field is different from previous row
                                        const showGrouped = index === 0 ||
                                            data[index - 1].UNIT_NAME !== row.UNIT_NAME ||
                                            data[index - 1].ASSET_NAME !== row.ASSET_NAME ||
                                            data[index - 1].DESCRIPTION !== row.DESCRIPTION ||
                                            data[index - 1].RISK_LEVEL !== row.RISK_LEVEL;
                                        const rowNumber = showGrouped ? (data.slice(0, index).filter((r, i) =>
                                            i === 0 ||
                                            data[i - 1].UNIT_NAME !== r.UNIT_NAME ||
                                            data[i - 1].ASSET_NAME !== r.ASSET_NAME ||
                                            data[i - 1].DESCRIPTION !== r.DESCRIPTION ||
                                            data[i - 1].RISK_LEVEL !== r.RISK_LEVEL
                                        ).length + 1) : null;

                                        // Format TMSF_VALUE: 2 decimals, blank if zero
                                        const formatTmsf = (value: any) => {
                                            if (value === null || value === undefined || value === '') return '';
                                            const num = Number(value);
                                            if (Number.isNaN(num) || num === 0) return '';
                                            return num.toFixed(2);
                                        };

                                        return (
                                            <tr key={index} className="hover:bg-gray-50 dark:hover:bg-gray-700">
                                                <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">
                                                    {showGrouped ? rowNumber : ''}
                                                </td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                    {showGrouped ? (row.UNIT_NAME || '-') : ''}
                                                </td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                    {showGrouped ? (row.ASSET_NAME || '-') : ''}
                                                </td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                    {showGrouped ? (row.DESCRIPTION || '-') : ''}
                                                </td>
                                                <td
                                                    className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100"
                                                    style={{
                                                        backgroundColor: showGrouped && row.COLOR
                                                            ? (row.COLOR.startsWith('#') ? row.COLOR : `#${row.COLOR}`)
                                                            : 'transparent'
                                                    }}
                                                >
                                                    {showGrouped ? (row.RISK_LEVEL || '-') : ''}
                                                </td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.DAMAGE_TYPE || '-'}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{formatTmsf(row.TMSF_VALUE)}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.INSTRUSIVE || '-'}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.INSP_TECH || '-'}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.INSP_DESC || '-'}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.INSP_EFFECT || '-'}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.DATE_OF_LAST || '-'}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.INSP_YEAR || '-'}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.YEAR_OF_ANALYSIS || '-'}</td>
                                                {yearColumns.map(year => (
                                                    <td key={year} className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">
                                                        {Number(row.INSP_YEAR) === year ? 'X' : ''}
                                                    </td>
                                                ))}
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.REMARKS || '-'}</td>
                                            </tr>
                                        );
                                    })}
                                </tbody>
                                    </table>
                                );
                            })()}
                        </div>
                    )}
                </div>

                {/* Modal Footer */}
                <div className="flex items-center justify-end gap-3 p-5 border-t border-gray-200 dark:border-gray-700">
                    <button
                        onClick={handleExportToExcel}
                        className="btn btn-primary"
                        disabled={loading || data.length === 0}
                    >
                        Save
                    </button>
                    <button
                        onClick={onClose}
                        className="btn btn-outline-danger"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
};

export default Report101;
