'use client';

import React from 'react';
import * as XLSX from 'xlsx-js-style';
import { useSession } from 'next-auth/react';

interface Report93Props {
    isOpen: boolean;
    onClose: () => void;
    data: any[];
    loading: boolean;
    reportTitle?: string;
}

const Report93: React.FC<Report93Props> = ({ isOpen, onClose, data, loading, reportTitle }) => {
    const { data: session } = useSession();

    if (!isOpen) return null;

    const getUserName = () => {
        return session?.user?.name || session?.user?.email || 'System User';
    };

    // Handle Excel export
    const handleExportToExcel = () => {
        const now = new Date();
        const dateTimeStr = now.toISOString().replace('T', ' ').substring(0, 19);
        const userName = getUserName();
        const title = reportTitle || 'Report 9-3';

        const ws = XLSX.utils.aoa_to_sheet([]);

        // Row 1: Title
        XLSX.utils.sheet_add_aoa(ws, [[title]], { origin: 'A1' });

        // Row 2: Empty row

        // Row 3: Headers
        const headers = ['No.', 'Inspection Year', 'Piping', 'Equipment', 'Total'];
        XLSX.utils.sheet_add_aoa(ws, [headers], { origin: 'A3' });

        // Calculate totals
        let totalPiping = 0;
        let totalEquipment = 0;
        let totalGrandTotal = 0;

        // Row 4+: Data
        const dataRows = data.map((row, index) => {
            const piping = Number(row.piping) || 0;
            const equipment = Number(row.equipment) || 0;
            const rowTotal = piping + equipment;

            totalPiping += piping;
            totalEquipment += equipment;
            totalGrandTotal += rowTotal;

            return [
                index + 1,
                row.insp_year || '',
                piping || '',
                equipment || '',
                rowTotal > 0 ? rowTotal : ''
            ];
        });
        XLSX.utils.sheet_add_aoa(ws, dataRows, { origin: 'A4' });

        // Add Total row
        const totalRowIndex = 4 + data.length;
        const totalRow = [
            '',
            'Total',
            totalPiping || '',
            totalEquipment || '',
            totalGrandTotal || ''
        ];
        XLSX.utils.sheet_add_aoa(ws, [totalRow], { origin: `A${totalRowIndex}` });

        // Footer rows (after data and total row)
        const footerStartRow = 4 + data.length + 1 + 1; // +1 for total row, +1 for empty row
        const footerText = `Report generated by ${userName} on ${dateTimeStr}`;
        XLSX.utils.sheet_add_aoa(ws, [[footerText]], { origin: `A${footerStartRow}` });

        // Apply cell styles with colors
        const range = XLSX.utils.decode_range(ws['!ref'] || 'A1');

        // Define border style
        const borderStyle = {
            top: { style: 'thin', color: { rgb: '000000' } },
            bottom: { style: 'thin', color: { rgb: '000000' } },
            left: { style: 'thin', color: { rgb: '000000' } },
            right: { style: 'thin', color: { rgb: '000000' } }
        };

        // Style the title (Row 1) - Bold, large, centered
        const titleCell = ws['A1'];
        if (titleCell) {
            titleCell.s = {
                font: { bold: true, sz: 16, color: { rgb: '000000' } },
                alignment: { horizontal: 'center', vertical: 'center' }
            };
        }

        // Merge title across all columns
        ws['!merges'] = ws['!merges'] || [];
        ws['!merges'].push({ s: { r: 0, c: 0 }, e: { r: 0, c: 4 } }); // Merge A1:E1

        // Style the header row (Row 3) - bold with gray background and borders
        for (let col = 0; col < 5; col++) {
            const cellAddress = XLSX.utils.encode_cell({ r: 2, c: col }); // Row 3 (index 2)
            if (!ws[cellAddress]) continue;
            ws[cellAddress].s = {
                font: { bold: true, color: { rgb: '000000' } },
                fill: { fgColor: { rgb: 'D3D3D3' } },
                alignment: { horizontal: 'center', vertical: 'center' },
                border: borderStyle
            };
        }

        // Apply styles to all data cells (starting from Row 4)
        for (let row = 0; row < data.length; row++) {
            for (let col = 0; col < 5; col++) {
                const cellAddress = XLSX.utils.encode_cell({ r: row + 3, c: col }); // Data starts at row 4 (index 3)
                if (!ws[cellAddress]) continue;

                // Base style with borders
                const baseStyle: any = {
                    alignment: { horizontal: 'center', vertical: 'center' },
                    border: borderStyle
                };

                ws[cellAddress].s = baseStyle;
            }
        }

        // Style the Total row - bold with borders
        const totalRowIdx = totalRowIndex - 1; // Convert to 0-based index
        for (let col = 0; col < 5; col++) {
            const cellAddress = XLSX.utils.encode_cell({ r: totalRowIdx, c: col });
            if (!ws[cellAddress]) continue;
            ws[cellAddress].s = {
                font: { bold: true, color: { rgb: '000000' } },
                alignment: { horizontal: 'center', vertical: 'center' },
                border: borderStyle
            };
        }

        // Style the footer (italic, gray)
        const footerRowNumber = footerStartRow;
        const footerCell = ws[`A${footerRowNumber}`];
        if (footerCell) {
            footerCell.s = {
                font: { italic: true, color: { rgb: '666666' } },
                alignment: { horizontal: 'left', vertical: 'center' }
            };
        }

        // Merge footer across all columns
        ws['!merges'].push({ s: { r: footerRowNumber - 1, c: 0 }, e: { r: footerRowNumber - 1, c: 4 } });

        // Set column widths
        ws['!cols'] = [
            { wch: 8 },  // No.
            { wch: 20 }, // Inspection Year
            { wch: 15 }, // Piping
            { wch: 15 }, // Equipment
            { wch: 15 }  // Total
        ];

        // Create workbook and add worksheet
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'Report 9-3');

        // Generate and download file
        XLSX.writeFile(wb, `report_9_3_${new Date().toISOString().slice(0, 10)}.xlsx`);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50" onClick={onClose}>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-[95vw] w-full mx-4 max-h-[90vh] overflow-hidden" onClick={(e) => e.stopPropagation()}>
                {/* Modal Header */}
                <div className="flex items-center justify-between p-5 border-b border-gray-200 dark:border-gray-700">
                    <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
                        {reportTitle || 'Report 9-3'}
                    </h3>
                    <button
                        onClick={onClose}
                        className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
                    >
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                {/* Modal Body */}
                <div className="overflow-auto max-h-[calc(90vh-140px)]">
                    {loading ? (
                        <div className="flex items-center justify-center py-12">
                            <div className="text-center">
                                <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
                                <p className="mt-4 text-gray-600 dark:text-gray-400">Loading report...</p>
                            </div>
                        </div>
                    ) : data.length === 0 ? (
                        <div className="flex items-center justify-center py-12">
                            <p className="text-gray-500 dark:text-gray-400">No data available</p>
                        </div>
                    ) : (
                        <div className="p-5">
                            {(() => {
                                // Calculate totals
                                let totalPiping = 0;
                                let totalEquipment = 0;
                                let totalGrandTotal = 0;

                                data.forEach(row => {
                                    const piping = Number(row.piping) || 0;
                                    const equipment = Number(row.equipment) || 0;
                                    totalPiping += piping;
                                    totalEquipment += equipment;
                                    totalGrandTotal += piping + equipment;
                                });

                                return (
                                    <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                                        <thead className="bg-gray-50 dark:bg-gray-900">
                                            <tr>
                                                <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">No.</th>
                                                <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Inspection Year</th>
                                                <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Piping</th>
                                                <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Equipment</th>
                                                <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                                            {data.map((row, index) => {
                                                const piping = Number(row.piping) || 0;
                                                const equipment = Number(row.equipment) || 0;
                                                const rowTotal = piping + equipment;

                                                return (
                                                    <tr key={index} className="hover:bg-gray-50 dark:hover:bg-gray-700">
                                                        <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">
                                                            {index + 1}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">
                                                            {row.insp_year || '-'}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">
                                                            {piping || '-'}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">
                                                            {equipment || '-'}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">
                                                            {rowTotal > 0 ? rowTotal : '-'}
                                                        </td>
                                                    </tr>
                                                );
                                            })}
                                            {/* Total Row */}
                                            <tr className="bg-gray-100 dark:bg-gray-700 font-bold">
                                                <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100"></td>
                                                <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">Total</td>
                                                <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">
                                                    {totalPiping || '-'}
                                                </td>
                                                <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">
                                                    {totalEquipment || '-'}
                                                </td>
                                                <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">
                                                    {totalGrandTotal || '-'}
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                );
                            })()}
                        </div>
                    )}
                </div>

                {/* Modal Footer */}
                <div className="flex items-center justify-end gap-3 p-5 border-t border-gray-200 dark:border-gray-700">
                    <button
                        onClick={handleExportToExcel}
                        className="btn btn-primary"
                        disabled={loading || data.length === 0}
                    >
                        Save
                    </button>
                    <button
                        onClick={onClose}
                        className="btn btn-outline-danger"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
};

export default Report93;
