'use client';

import React from 'react';
import * as XLSX from 'xlsx-js-style';
import { useSession } from 'next-auth/react';

interface Report43Props {
    isOpen: boolean;
    onClose: () => void;
    data: any[];
    loading: boolean;
    reportTitle?: string;
}

const Report43: React.FC<Report43Props> = ({ isOpen, onClose, data, loading, reportTitle }) => {
    const { data: session } = useSession();

    if (!isOpen) return null;

    const getUserName = () => session?.user?.name || session?.user?.email || 'System User';

    const formatNumber = (value: any) => {
        if (value === null || value === undefined || value === '') return '';
        const num = Number(value);
        if (Number.isNaN(num)) return String(value);
        return Number.isInteger(num) ? num.toString() : num.toFixed(2);
    };

    // Handle Excel export
    const handleExportToExcel = () => {
        const now = new Date();
        const dateTimeStr = now.toISOString().replace('T', ' ').substring(0, 19);
        const userName = getUserName();
        const title = reportTitle || 'Report 4-3';

        const ws = XLSX.utils.aoa_to_sheet([]);

        // Title
        XLSX.utils.sheet_add_aoa(ws, [[title]], { origin: 'A1' });

        // Headers
        const headers = [
            'No.',
            'Asset Name',
            'Risk Level',
            'Damage Type',
            'TMSF Value',
            'Inspection Tech',
            'Inspection Year',
            'Remarks'
        ];
        XLSX.utils.sheet_add_aoa(ws, [headers], { origin: 'A3' });

        let lastAssetName: string | null = null;
        let groupCounter = 0;
        const dataRows = data.map((row) => {
            const isNewAsset = row.ASSET_NAME !== lastAssetName;
            if (isNewAsset) {
                groupCounter += 1;
                lastAssetName = row.ASSET_NAME;
            }

            return [
                isNewAsset ? groupCounter : '',
                isNewAsset ? (row.ASSET_NAME || '') : '',
                isNewAsset ? (row.RISK_LEVEL || '') : '',
                row.DAMAGE_TYPE || '',
                formatNumber(row.TMSF_VALUE),
                row.INSP_TECH || '',
                row.INSP_YEAR || '',
                row.REMARKS || ''
            ];
        });
        XLSX.utils.sheet_add_aoa(ws, dataRows, { origin: 'A4' });

        const footerStartRow = 4 + data.length + 1;
        const footerText = `Report generated by ${userName} on ${dateTimeStr}`;
        XLSX.utils.sheet_add_aoa(ws, [[footerText]], { origin: `A${footerStartRow}` });

        const borderStyle = {
            top: { style: 'thin', color: { rgb: '000000' } },
            bottom: { style: 'thin', color: { rgb: '000000' } },
            left: { style: 'thin', color: { rgb: '000000' } },
            right: { style: 'thin', color: { rgb: '000000' } }
        };

        // Style title
        const titleCell = ws['A1'];
        if (titleCell) {
            titleCell.s = {
                font: { bold: true, sz: 16, color: { rgb: '000000' } },
                alignment: { horizontal: 'center', vertical: 'center' }
            };
        }

        // Merge title across all columns
        ws['!merges'] = ws['!merges'] || [];
        ws['!merges'].push({ s: { r: 0, c: 0 }, e: { r: 0, c: headers.length - 1 } });

        // Style headers
        for (let col = 0; col < headers.length; col++) {
            const cellAddress = XLSX.utils.encode_cell({ r: 2, c: col });
            if (!ws[cellAddress]) continue;
            ws[cellAddress].s = {
                font: { bold: true, color: { rgb: '000000' } },
                fill: { fgColor: { rgb: 'D3D3D3' } },
                alignment: { horizontal: 'center', vertical: 'center' },
                border: borderStyle
            };
        }

        // Style data cells
        for (let row = 0; row < data.length; row++) {
            for (let col = 0; col < headers.length; col++) {
                const cellAddress = XLSX.utils.encode_cell({ r: row + 3, c: col });
                if (!ws[cellAddress]) continue;

                const isNewAsset = row === 0 || data[row - 1].ASSET_NAME !== data[row].ASSET_NAME;
                const baseStyle: any = {
                    alignment: {
                        horizontal: col === 0 ? 'center' : col === 4 ? 'right' : 'left',
                        vertical: 'center'
                    },
                    border: borderStyle
                };

                if (col === 4) {
                    baseStyle.numFmt = '0.00';
                }

                // Apply risk color only when there is a value to show
                if (col === 2 && isNewAsset && data[row].RISK_LEVEL) {
                    const rawColor = (data[row].COLOR ?? '').toString();
                    const normalizedColor = rawColor.startsWith('#') ? rawColor.slice(1) : rawColor;
                    if (normalizedColor) {
                        baseStyle.fill = { fgColor: { rgb: normalizedColor } };
                    }
                }

                ws[cellAddress].s = baseStyle;
            }
        }

        // Footer styling and merge
        const footerRowNumber = footerStartRow;
        const footerCell = ws[`A${footerRowNumber}`];
        if (footerCell) {
            footerCell.s = {
                font: { italic: true, color: { rgb: '666666' } },
                alignment: { horizontal: 'left', vertical: 'center' }
            };
        }
        ws['!merges'].push({ s: { r: footerRowNumber - 1, c: 0 }, e: { r: footerRowNumber - 1, c: headers.length - 1 } });

        // Column widths
        ws['!cols'] = [
            { wch: 6 },   // No.
            { wch: 30 },  // Asset Name
            { wch: 18 },  // Risk Level
            { wch: 20 },  // Damage Type
            { wch: 12 },  // TMSF Value
            { wch: 20 },  // Inspection Tech
            { wch: 14 },  // Inspection Year
            { wch: 30 }   // Remarks
        ];

        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'Report 4-3');

        XLSX.writeFile(wb, `report_4_3_${new Date().toISOString().slice(0, 10)}.xlsx`);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50" onClick={onClose}>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-[95vw] w-full mx-4 max-h-[90vh] overflow-hidden" onClick={(e) => e.stopPropagation()}>
                {/* Modal Header */}
                <div className="flex items-center justify-between p-5 border-b border-gray-200 dark:border-gray-700">
                    <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
                        {reportTitle || 'Report 4-3'}
                    </h3>
                    <button
                        onClick={onClose}
                        className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
                    >
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                {/* Modal Body */}
                <div className="p-5 overflow-auto max-h-[calc(90vh-140px)]">
                    {loading ? (
                        <div className="flex items-center justify-center py-12">
                            <div className="text-center">
                                <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
                                <p className="mt-4 text-gray-600 dark:text-gray-400">Loading report...</p>
                            </div>
                        </div>
                    ) : data.length === 0 ? (
                        <div className="flex items-center justify-center py-12">
                            <p className="text-gray-500 dark:text-gray-400">No data available</p>
                        </div>
                    ) : (
                        <div className="overflow-x-auto">
                            <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                                <thead className="bg-gray-50 dark:bg-gray-900">
                                    <tr>
                                        <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">No.</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Asset Name</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Risk Level</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Damage Type</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">TMSF Value</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Inspection Tech</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Inspection Year</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Remarks</th>
                                    </tr>
                                </thead>
                                <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                                    {data.map((row, index) => {
                                        const isNewAsset = index === 0 || data[index - 1].ASSET_NAME !== row.ASSET_NAME;
                                        const rowNumber = isNewAsset
                                            ? data
                                                  .slice(0, index + 1)
                                                  .filter((r, i) => i === 0 || data[i - 1].ASSET_NAME !== r.ASSET_NAME).length
                                            : null;

                                        return (
                                            <tr key={index} className="hover:bg-gray-50 dark:hover:bg-gray-700">
                                                <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">
                                                    {isNewAsset ? rowNumber : ''}
                                                </td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                    {isNewAsset ? (row.ASSET_NAME || '-') : ''}
                                                </td>
                                                <td
                                                    className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100"
                                                    style={{
                                                        backgroundColor:
                                                            isNewAsset && row.RISK_LEVEL
                                                                ? (row.COLOR
                                                                    ? (String(row.COLOR).startsWith('#') ? String(row.COLOR) : `#${row.COLOR}`)
                                                                    : 'transparent')
                                                                : 'transparent'
                                                    }}
                                                >
                                                    {isNewAsset ? (row.RISK_LEVEL || '-') : ''}
                                                </td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.DAMAGE_TYPE || '-'}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{formatNumber(row.TMSF_VALUE) || '-'}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.INSP_TECH || '-'}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.INSP_YEAR || '-'}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.REMARKS || '-'}</td>
                                            </tr>
                                        );
                                    })}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>

                {/* Modal Footer */}
                <div className="flex items-center justify-end gap-3 p-5 border-t border-gray-200 dark:border-gray-700">
                    <button
                        onClick={handleExportToExcel}
                        className="btn btn-primary"
                        disabled={loading || data.length === 0}
                    >
                        Save
                    </button>
                    <button
                        onClick={onClose}
                        className="btn btn-outline-danger"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
};

export default Report43;
