'use client';

import React from 'react';
import * as XLSX from 'xlsx-js-style';
import { useSession } from 'next-auth/react';

interface Report67Props {
    isOpen: boolean;
    onClose: () => void;
    data: any[];
    loading: boolean;
    reportTitle?: string;
}

const Report67: React.FC<Report67Props> = ({ isOpen, onClose, data, loading, reportTitle }) => {
    const { data: session } = useSession();

    if (!isOpen) return null;

    const getUserName = () => {
        return session?.user?.name || session?.user?.email || 'System User';
    };

    const formatNumber = (value: any) => {
        if (value === null || value === undefined || value === '') return '';
        const num = Number(value);
        if (Number.isNaN(num)) return String(value);
        return Number.isInteger(num) ? num.toString() : num.toFixed(2);
    };

    // Handle Excel export
    const handleExportToExcel = () => {
        const now = new Date();
        const dateTimeStr = now.toISOString().replace('T', ' ').substring(0, 19);
        const userName = getUserName();
        const title = reportTitle || 'Report 6-7';

        const ws = XLSX.utils.aoa_to_sheet([]);

        XLSX.utils.sheet_add_aoa(ws, [[title]], { origin: 'A1' });

        const headers = ['No.', 'Asset Name', 'Part', 'POF Level', 'COF Flame', 'COF Health', 'COF Business', 'Risk Category', 'Remarks'];
        XLSX.utils.sheet_add_aoa(ws, [headers], { origin: 'A3' });

        const numericValue = (value: any) => {
            const num = Number(value);
            return Number.isNaN(num) ? '' : num;
        };

        const dataRows = data.map((row, index) => [
            index + 1,
            // row.assetID ?? row.ASSET_ID ?? '',
            row.ASSET_NAME || '',
            row.PART || '',
            numericValue(row.POF_LEVEL),
            numericValue(row.COF_FLAME),
            numericValue(row.COF_HEALTH),
            numericValue(row.COF_BUSINESS),
            row.RISK_CATEGORY || '',
            row.REMARKS || ''
        ]);
        XLSX.utils.sheet_add_aoa(ws, dataRows, { origin: 'A4' });

        const footerStartRow = 4 + data.length + 1;
        const footerText = `Report generated by ${userName} on ${dateTimeStr}`;
        XLSX.utils.sheet_add_aoa(ws, [[footerText]], { origin: `A${footerStartRow}` });

        const range = XLSX.utils.decode_range(ws['!ref'] || 'A1');

        const borderStyle = {
            top: { style: 'thin', color: { rgb: '000000' } },
            bottom: { style: 'thin', color: { rgb: '000000' } },
            left: { style: 'thin', color: { rgb: '000000' } },
            right: { style: 'thin', color: { rgb: '000000' } }
        };

        const titleCell = ws['A1'];
        if (titleCell) {
            titleCell.s = {
                font: { bold: true, sz: 16, color: { rgb: '000000' } },
                alignment: { horizontal: 'center', vertical: 'center' }
            };
        }

        ws['!merges'] = ws['!merges'] || [];
        ws['!merges'].push({ s: { r: 0, c: 0 }, e: { r: 0, c: 8 } });

        for (let col = 0; col < 9; col++) {
            const cellAddress = XLSX.utils.encode_cell({ r: 2, c: col });
            if (!ws[cellAddress]) continue;
            ws[cellAddress].s = {
                font: { bold: true, color: { rgb: '000000' } },
                fill: { fgColor: { rgb: 'D3D3D3' } },
                alignment: { horizontal: 'center', vertical: 'center' },
                border: borderStyle
            };
        }

        for (let row = 0; row < data.length; row++) {
            for (let col = 0; col < 9; col++) {
                const cellAddress = XLSX.utils.encode_cell({ r: row + 3, c: col });
                if (!ws[cellAddress]) continue;

                const baseStyle: any = {
                    alignment: {
                        horizontal: col === 0 ? 'center' : [4, 5, 6, 7].includes(col) ? 'right' : 'left',
                        vertical: 'center'
                    },
                    border: borderStyle
                };

                if ([4, 5, 6, 7].includes(col)) {
                    baseStyle.numFmt = '0.00';
                }

                ws[cellAddress].s = baseStyle;
            }
        }

        const footerRowNumber = footerStartRow;
        const footerCell = ws[`A${footerRowNumber}`];
        if (footerCell) {
            footerCell.s = {
                font: { italic: true, color: { rgb: '666666' } },
                alignment: { horizontal: 'left', vertical: 'center' }
            };
        }

        ws['!merges'].push({ s: { r: footerRowNumber - 1, c: 0 }, e: { r: footerRowNumber - 1, c: 8 } });

        ws['!cols'] = [
            { wch: 8 },  // No.
            // { wch: 12 }, // Asset ID
            { wch: 28 }, // Asset Name
            { wch: 18 }, // Part
            { wch: 12 }, // POF Level
            { wch: 12 }, // COF Flame
            { wch: 12 }, // COF Health
            { wch: 12 }, // COF Business
            { wch: 18 }, // Risk Category
            { wch: 30 }  // Remarks
        ];

        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'Report 6-7');

        XLSX.writeFile(wb, `report_6_7_${new Date().toISOString().slice(0, 10)}.xlsx`);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50" onClick={onClose}>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-[95vw] w-full mx-4 max-h-[90vh] overflow-hidden" onClick={(e) => e.stopPropagation()}>
                {/* Modal Header */}
                <div className="flex items-center justify-between p-5 border-b border-gray-200 dark:border-gray-700">
                    <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
                        {reportTitle || 'Report 6-7'}
                    </h3>
                    <button
                        onClick={onClose}
                        className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
                    >
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                {/* Modal Body */}
                <div className="p-5 overflow-auto max-h-[calc(90vh-140px)]">
                    {loading ? (
                        <div className="flex items-center justify-center py-12">
                            <div className="text-center">
                                <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
                                <p className="mt-4 text-gray-600 dark:text-gray-400">Loading report...</p>
                            </div>
                        </div>
                    ) : data.length === 0 ? (
                        <div className="flex items-center justify-center py-12">
                            <p className="text-gray-500 dark:text-gray-400">No data available</p>
                        </div>
                    ) : (
                        <div className="overflow-x-auto">
                            <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                                <thead className="bg-gray-50 dark:bg-gray-900">
                                    <tr>
                                        <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">No.</th>
                                        {/* <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Asset ID</th> */}
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Asset Name</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Part</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">POF Level</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">COF Flame</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">COF Health</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">COF Business</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Risk Category</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Remarks</th>
                                    </tr>
                                </thead>
                                <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                                    {data.map((row, index) => (
                                        <tr key={index} className="hover:bg-gray-50 dark:hover:bg-gray-700">
                                            <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">{index + 1}</td>
                                            {/* <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.assetID ?? row.ASSET_ID ?? '-'}</td> */}
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.ASSET_NAME || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.PART || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{formatNumber(row.POF_LEVEL) || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{formatNumber(row.COF_FLAME) || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{formatNumber(row.COF_HEALTH) || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{formatNumber(row.COF_BUSINESS) || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.RISK_CATEGORY || '-'}</td>
                                            <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.REMARKS || '-'}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>

                {/* Modal Footer */}
                <div className="flex items-center justify-end gap-3 p-5 border-t border-gray-200 dark:border-gray-700">
                    <button
                        onClick={handleExportToExcel}
                        className="btn btn-primary"
                        disabled={loading || data.length === 0}
                    >
                        Save
                    </button>
                    <button
                        onClick={onClose}
                        className="btn btn-outline-danger"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
};

export default Report67;
