'use client';

import React from 'react';
import * as XLSX from 'xlsx-js-style';
import { useSession } from 'next-auth/react';

interface ReportInspectionWorkpackProps {
    isOpen: boolean;
    onClose: () => void;
    data: any[];
    riskMatrix?: any[];
    loading: boolean;
    reportTitle?: string;
    year?: string | number;
}

const ReportInspectionWorkpack: React.FC<ReportInspectionWorkpackProps> = ({ isOpen, onClose, data, riskMatrix = [], loading, reportTitle, year }) => {
    const { data: session } = useSession();

    if (!isOpen) return null;

    const getUserName = () => session?.user?.name || session?.user?.email || 'System User';

    const formatNumber = (value: any) => {
        if (value === null || value === undefined || value === '') return '';
        const num = Number(value);
        if (Number.isNaN(num)) return String(value);
        return Number.isInteger(num) ? num.toString() : num.toFixed(2);
    };

    // Handle Excel export
    const handleExportToExcel = () => {
        const now = new Date();
        const dateTimeStr = now.toISOString().replace('T', ' ').substring(0, 19);
        const userName = getUserName();
        const title = reportTitle || 'Inspection Workpack Report';

        const ws = XLSX.utils.aoa_to_sheet([]);

        // Title
        XLSX.utils.sheet_add_aoa(ws, [[title]], { origin: 'A1' });

        // Headers
        const headers = [
            'No.',
            'Asset Name',
            'Description',
            'Category',
            'Risk Level',
            'Damage Mechanism',
            'Inspection Technique',
            'Status',
            'Effectiveness',
            'Coverage',
            'Unit Cost US$',
            'Location',
            'PFD No',
            'P&ID No'
        ];
        XLSX.utils.sheet_add_aoa(ws, [headers], { origin: 'A3' });

        // Group data by parent for Excel
        const groupedExcelData = groupDataByParent();
        const allRows: any[] = [];

        groupedExcelData.forEach(([parentKey, children]) => {
            const parentName = children[0]?.parent_name || 'No Parent';
            const totalAssets = children.length;
            const totalCost = children.reduce((sum, row) => {
                const cost = Number(row['Unit Cost US$']);
                return sum + (isNaN(cost) ? 0 : cost);
            }, 0);

            // Add parent header row with totals
            const parentHeaderText = `${parentName} - Total Assets: ${totalAssets} | Total Cost: US$ ${totalCost.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
            allRows.push([parentHeaderText, '', '', '', '', '', '', '', '', '', '', '', '', '']);

            // Add child rows
            children.forEach((row, index) => {
                allRows.push([
                    index + 1,
                    row['Asset Name'] || '',
                    row.description || '',
                    row.category || '',
                    row['Risk Level'] || '',
                    row['Damage Mechanism'] || '',
                    row['Inspection Technique'] || '',
                    row.Status || '',
                    row.Effectiveness || '',
                    row.Coverage || '',
                    formatNumber(row['Unit Cost US$']),
                    row.location || '',
                    row['PFD No'] || '',
                    row['P&ID No'] || ''
                ]);
            });
        });

        XLSX.utils.sheet_add_aoa(ws, allRows, { origin: 'A4' });

        const footerStartRow = 4 + allRows.length + 1;
        const footerText = `Report generated by ${userName} on ${dateTimeStr}`;
        XLSX.utils.sheet_add_aoa(ws, [[footerText]], { origin: `A${footerStartRow}` });

        const borderStyle = {
            top: { style: 'thin', color: { rgb: '000000' } },
            bottom: { style: 'thin', color: { rgb: '000000' } },
            left: { style: 'thin', color: { rgb: '000000' } },
            right: { style: 'thin', color: { rgb: '000000' } }
        };

        // Style title
        const titleCell = ws['A1'];
        if (titleCell) {
            titleCell.s = {
                font: { bold: true, sz: 16, color: { rgb: '000000' } },
                alignment: { horizontal: 'center', vertical: 'center' }
            };
        }

        // Merge title across all columns
        ws['!merges'] = ws['!merges'] || [];
        ws['!merges'].push({ s: { r: 0, c: 0 }, e: { r: 0, c: headers.length - 1 } });

        // Style headers
        for (let c = 0; c < headers.length; c++) {
            const cellAddress = XLSX.utils.encode_cell({ r: 2, c });
            if (!ws[cellAddress]) continue;
            ws[cellAddress].s = {
                font: { bold: true, color: { rgb: 'FFFFFF' } },
                fill: { fgColor: { rgb: '4472C4' } },
                alignment: { horizontal: 'center', vertical: 'center' },
                border: borderStyle
            };
        }

        // Style data rows (with parent grouping)
        let currentRow = 3; // Start after headers (row 3 in 0-indexed)
        groupedExcelData.forEach(([parentKey, children]) => {
            // Style parent header row
            const parentRowAddress = XLSX.utils.encode_cell({ r: currentRow, c: 0 });
            if (ws[parentRowAddress]) {
                ws[parentRowAddress].s = {
                    font: { bold: true, color: { rgb: '000000' } },
                    fill: { fgColor: { rgb: 'DAEEF3' } },
                    alignment: { horizontal: 'left', vertical: 'center' },
                    border: borderStyle
                };
            }
            // Merge parent row across all columns
            ws['!merges'].push({ s: { r: currentRow, c: 0 }, e: { r: currentRow, c: headers.length - 1 } });
            currentRow++;

            // Style child rows
            for (let i = 0; i < children.length; i++) {
                for (let c = 0; c < headers.length; c++) {
                    const cellAddress = XLSX.utils.encode_cell({ r: currentRow, c });
                    if (!ws[cellAddress]) continue;
                    ws[cellAddress].s = {
                        alignment: { horizontal: c === 0 ? 'center' : 'left', vertical: 'center' },
                        border: borderStyle
                    };
                }
                currentRow++;
            }
        });

        // Style footer
        const footerRowNumber = footerStartRow;
        const footerCell = ws[`A${footerRowNumber}`];
        if (footerCell) {
            footerCell.s = {
                font: { italic: true, color: { rgb: '666666' } },
                alignment: { horizontal: 'left', vertical: 'center' }
            };
        }
        ws['!merges'].push({ s: { r: footerRowNumber - 1, c: 0 }, e: { r: footerRowNumber - 1, c: headers.length - 1 } });

        // Column widths
        ws['!cols'] = [
            { wch: 6 },   // No.
            { wch: 25 },  // Asset Name
            { wch: 30 },  // Description
            { wch: 15 },  // Category
            { wch: 15 },  // Risk Level
            { wch: 25 },  // Damage Mechanism
            { wch: 25 },  // Inspection Technique
            { wch: 12 },  // Status
            { wch: 15 },  // Effectiveness
            { wch: 12 },  // Coverage
            { wch: 15 },  // Unit Cost US$
            { wch: 20 },  // Location
            { wch: 15 },  // PFD No
            { wch: 15 }   // P&ID No
        ];

        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'Inspection Workpack');

        XLSX.writeFile(wb, `inspection_workpack_${new Date().toISOString().slice(0, 10)}.xlsx`);
    };

    // Get RGB color for risk level from risk matrix
    const getRiskLevelColor = (row: any) => {
        const riskLevel = row['Risk Level'];
        if (!riskLevel || !riskMatrix || riskMatrix.length === 0) {
            return 'transparent';
        }

        // Find matching risk level in risk matrix
        const matrixEntry = riskMatrix.find((entry: any) => entry.Risk_Level === riskLevel);
        if (matrixEntry && matrixEntry.color) {
            // Add # prefix if not present
            return matrixEntry.color.startsWith('#') ? matrixEntry.color : `#${matrixEntry.color}`;
        }

        return 'transparent';
    };

    // Calculate total budget estimation
    const calculateTotalBudget = () => {
        return data.reduce((total, row) => {
            const cost = Number(row['Unit Cost US$']);
            return total + (isNaN(cost) ? 0 : cost);
        }, 0);
    };

    const totalBudget = calculateTotalBudget();

    // Group data by parent
    const groupDataByParent = () => {
        const grouped: { [key: string]: any[] } = {};

        data.forEach((row) => {
            const parentKey = `${row.parent_id || 'null'}_${row.parent_name || 'No Parent'}`;
            if (!grouped[parentKey]) {
                grouped[parentKey] = [];
            }
            grouped[parentKey].push(row);
        });

        // Sort by parent_id ascending
        const sortedGroups = Object.entries(grouped).sort((a, b) => {
            const parentIdA = a[1][0]?.parent_id || 0;
            const parentIdB = b[1][0]?.parent_id || 0;
            return parentIdA - parentIdB;
        });

        return sortedGroups;
    };

    const groupedData = groupDataByParent();

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50" onClick={onClose}>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-[95vw] w-full mx-4 max-h-[90vh] overflow-hidden" onClick={(e) => e.stopPropagation()}>
                {/* Modal Header */}
                <div className="flex items-center justify-between p-5 border-b border-gray-200 dark:border-gray-700">
                    <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
                        {reportTitle || 'Inspection Workpack Report'}
                    </h3>
                    <button
                        onClick={onClose}
                        className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
                    >
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                {/* Modal Body */}
                <div className="p-5 overflow-auto max-h-[calc(90vh-140px)]">
                    {loading ? (
                        <div className="flex items-center justify-center py-12">
                            <div className="text-center">
                                <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
                                <p className="mt-4 text-gray-600 dark:text-gray-400">Loading report...</p>
                            </div>
                        </div>
                    ) : data.length === 0 ? (
                        <div className="flex items-center justify-center py-12">
                            <p className="text-gray-500 dark:text-gray-400">
                                {year ? `No workpack available for year ${year}` : 'No workpack available'}
                            </p>
                        </div>
                    ) : (
                        <>
                            {/* Total Budget Estimation */}
                            <div className="mb-4 p-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg">
                                <div className="flex items-center justify-between">
                                    <span className="text-lg font-semibold text-gray-700 dark:text-gray-300">
                                        Total Budget Estimation:
                                    </span>
                                    <span className="text-2xl font-bold text-blue-600 dark:text-blue-400">
                                        US$ {totalBudget.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                                    </span>
                                </div>
                            </div>

                            <div className="overflow-x-auto">
                            <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                                <thead className="bg-gray-50 dark:bg-gray-900">
                                    <tr>
                                        <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">No.</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Asset Name</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Description</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Category</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Risk Level</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Damage Mechanism</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Inspection Technique</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Status</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Effectiveness</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Coverage</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Unit Cost US$</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Location</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">PFD No</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">P&ID No</th>
                                    </tr>
                                </thead>
                                <tbody className="bg-white dark:bg-gray-800">
                                    {groupedData.map(([parentKey, children], groupIndex) => {
                                                        const parentName = children[0]?.parent_name || 'No Parent';
                                        const totalAssets = children.length;
                                        const totalCost = children.reduce((sum, row) => {
                                            const cost = Number(row['Unit Cost US$']);
                                            return sum + (isNaN(cost) ? 0 : cost);
                                        }, 0);
                                        return (
                                            <React.Fragment key={parentKey}>
                                                {/* Parent Header Row */}
                                                <tr className="bg-blue-100 dark:bg-blue-900/30 border-t-2 border-blue-300 dark:border-blue-700">
                                                    <td colSpan={14} className="px-4 py-3 text-sm font-bold text-gray-900 dark:text-gray-100">
                                                        <div className="flex items-center justify-between">
                                                            <span>{parentName}</span>
                                                            <span className="text-xs font-normal">
                                                                Total Assets: {totalAssets} | Total Cost: US$ {totalCost.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                                                            </span>
                                                        </div>
                                                    </td>
                                                </tr>
                                                {/* Child Rows */}
                                                {children.map((row, childIndex) => (
                                                    <tr key={`${parentKey}_${childIndex}`} className="hover:bg-gray-50 dark:hover:bg-gray-700 border-b border-gray-200 dark:border-gray-700">
                                                        <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">
                                                            {childIndex + 1}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                            {row['Asset Name'] || '-'}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                            {row.description || '-'}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                            {row.category || '-'}
                                                        </td>
                                                        <td
                                                            className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100"
                                                            style={{
                                                                backgroundColor: getRiskLevelColor(row)
                                                            }}
                                                        >
                                                            {row['Risk Level'] || '-'}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                            {row['Damage Mechanism'] || '-'}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                            {row['Inspection Technique'] || '-'}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                            {row.Status || '-'}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                            {row.Effectiveness || '-'}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                            {row.Coverage || '-'}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                            {formatNumber(row['Unit Cost US$'])}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                            {row.location || '-'}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                            {row['PFD No'] || '-'}
                                                        </td>
                                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                            {row['P&ID No'] || '-'}
                                                        </td>
                                                    </tr>
                                                ))}
                                            </React.Fragment>
                                        );
                                    })}
                                </tbody>
                            </table>
                        </div>
                        </>
                    )}
                </div>

                {/* Modal Footer */}
                <div className="flex items-center justify-between p-5 border-t border-gray-200 dark:border-gray-700">
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                        Total records: {data.length}
                    </p>
                    <div className="flex items-center gap-3">
                        <button
                            onClick={handleExportToExcel}
                            disabled={loading || data.length === 0}
                            className="px-4 py-2 text-sm font-medium text-white bg-success hover:bg-success/90 rounded-lg disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            Save
                        </button>
                        <button
                            onClick={onClose}
                            className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600 rounded-lg"
                        >
                            Close
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ReportInspectionWorkpack;
