'use client';

import React from 'react';
import * as XLSX from 'xlsx-js-style';
import { useSession } from 'next-auth/react';

interface Report21Props {
    isOpen: boolean;
    onClose: () => void;
    data: any[];
    loading: boolean;
    reportTitle?: string;
}

const Report21: React.FC<Report21Props> = ({ isOpen, onClose, data, loading, reportTitle }) => {
    const { data: session } = useSession();

    if (!isOpen) return null;

    // Get current user name from session
    const getUserName = () => {
        return session?.user?.name || session?.user?.email || 'System User';
    };

    // Handle Excel export
    const handleExportToExcel = () => {
        // Get current date and time
        const now = new Date();
        const dateTimeStr = now.toISOString().replace('T', ' ').substring(0, 19);
        const userName = getUserName();
        const title = reportTitle || 'Report 2-1';

        // Create worksheet with empty data first to manually control layout
        const ws = XLSX.utils.aoa_to_sheet([]);

        // Row 1: Title
        XLSX.utils.sheet_add_aoa(ws, [[title]], { origin: 'A1' });

        // Row 2: Empty row

        // Row 3: Headers
        const headers = ['No.', 'Unit', 'Category', 'Piping', 'Piping %', 'Equipment', 'Equipment %'];
        XLSX.utils.sheet_add_aoa(ws, [headers], { origin: 'A3' });

        // Row 4+: Data - Group by Unit (ASSET_NAME)
        const dataRows = data.map((row, index) => {
            // Check if this is the first row or if the ASSET_NAME is different from the previous row
            const showUnitAndNumber = index === 0 || data[index - 1].ASSET_NAME !== row.ASSET_NAME;
            const rowNumber = showUnitAndNumber ? (data.slice(0, index).filter((r, i) => i === 0 || data[i - 1].ASSET_NAME !== r.ASSET_NAME).length + 1) : '';

            return [
                rowNumber,
                showUnitAndNumber ? (row.ASSET_NAME || '') : '',
                row.RISK_NAME || '',
                row.PIPING || '',
                (row.PIPING_PCT != null && Number(row.PIPING_PCT) !== 0) ? row.PIPING_PCT : '',
                row.EQUIPMENT || '',
                (row.EQUIPMENT_PCT != null && Number(row.EQUIPMENT_PCT) !== 0) ? row.EQUIPMENT_PCT : ''
            ];
        });
        XLSX.utils.sheet_add_aoa(ws, dataRows, { origin: 'A4' });

        // Add Total Row
        const totalRowNumber = 4 + data.length; // Row after last data row
        const totalPiping = data.reduce((sum, row) => sum + (Number(row.PIPING) || 0), 0);
        const totalPipingPct = data.reduce((sum, row) => sum + (Number(row.PIPING_PCT) || 0), 0);
        const totalEquipment = data.reduce((sum, row) => sum + (Number(row.EQUIPMENT) || 0), 0);
        const totalEquipmentPct = data.reduce((sum, row) => sum + (Number(row.EQUIPMENT_PCT) || 0), 0);

        const totalRow = [
            '', // No.
            '', // Unit
            'TOTAL', // Category
            totalPiping,
            totalPipingPct !== 0 ? totalPipingPct : '',
            totalEquipment,
            totalEquipmentPct !== 0 ? totalEquipmentPct : ''
        ];
        XLSX.utils.sheet_add_aoa(ws, [totalRow], { origin: `A${totalRowNumber}` });

        // Footer rows (after total row)
        const footerStartRow = totalRowNumber + 2; // +1 for total row, +1 for empty row
        const footerText = `Report generated by ${userName} on ${dateTimeStr}`;
        XLSX.utils.sheet_add_aoa(ws, [[footerText]], { origin: `A${footerStartRow}` });

        // Apply cell styles with colors
        const range = XLSX.utils.decode_range(ws['!ref'] || 'A1');

        // Define border style
        const borderStyle = {
            top: { style: 'thin', color: { rgb: '000000' } },
            bottom: { style: 'thin', color: { rgb: '000000' } },
            left: { style: 'thin', color: { rgb: '000000' } },
            right: { style: 'thin', color: { rgb: '000000' } }
        };

        // Style the title (Row 1) - Bold, large, centered
        const titleCell = ws['A1'];
        if (titleCell) {
            titleCell.s = {
                font: { bold: true, sz: 16, color: { rgb: '000000' } },
                alignment: { horizontal: 'center', vertical: 'center' }
            };
        }

        // Merge title across all columns
        ws['!merges'] = ws['!merges'] || [];
        ws['!merges'].push({ s: { r: 0, c: 0 }, e: { r: 0, c: 6 } }); // Merge A1:G1

        // Style the header row (Row 3) - bold with gray background and borders
        for (let col = 0; col < 7; col++) {
            const cellAddress = XLSX.utils.encode_cell({ r: 2, c: col }); // Row 3 (index 2)
            if (!ws[cellAddress]) continue;
            ws[cellAddress].s = {
                font: { bold: true, color: { rgb: '000000' } },
                fill: { fgColor: { rgb: 'D3D3D3' } },
                alignment: { horizontal: 'center', vertical: 'center' },
                border: borderStyle
            };
        }

        // Apply styles to all data cells (starting from Row 4)
        for (let row = 0; row < data.length; row++) {
            for (let col = 0; col < 7; col++) {
                const cellAddress = XLSX.utils.encode_cell({ r: row + 3, c: col }); // Data starts at row 4 (index 3)
                if (!ws[cellAddress]) continue;

                // Base style with borders
                const baseStyle: any = {
                    alignment: { horizontal: col === 0 ? 'center' : 'left', vertical: 'center' },
                    border: borderStyle
                };

                // Add background color based on RISK_COLOR for Category column (col 2)
                if (col === 2 && data[row].RISK_COLOR) {
                    baseStyle.fill = { fgColor: { rgb: data[row].RISK_COLOR.replace('#', '') } };
                }

                // Add number format with 2 decimals for Piping % (col 4) and Equipment % (col 6)
                if (col === 4 || col === 6) {
                    baseStyle.numFmt = '0.00';
                }

                ws[cellAddress].s = baseStyle;
            }
        }

        // Style the total row (bold with gray background)
        for (let col = 0; col < 7; col++) {
            const cellAddress = XLSX.utils.encode_cell({ r: totalRowNumber - 1, c: col }); // totalRowNumber is 1-based, need 0-based
            if (!ws[cellAddress]) continue;

            const totalStyle: any = {
                font: { bold: true, color: { rgb: '000000' } },
                fill: { fgColor: { rgb: 'D3D3D3' } },
                alignment: { horizontal: col === 0 ? 'center' : 'left', vertical: 'center' },
                border: borderStyle
            };

            // Add number format with 2 decimals for Piping % (col 4) and Equipment % (col 6)
            if (col === 4 || col === 6) {
                totalStyle.numFmt = '0.00';
            }

            ws[cellAddress].s = totalStyle;
        }

        // Style the footer (italic, gray)
        const footerRowNumber = footerStartRow;
        const footerCell = ws[`A${footerRowNumber}`];
        if (footerCell) {
            footerCell.s = {
                font: { italic: true, color: { rgb: '666666' } },
                alignment: { horizontal: 'left', vertical: 'center' }
            };
        }

        // Merge footer across all columns
        ws['!merges'].push({ s: { r: footerRowNumber - 1, c: 0 }, e: { r: footerRowNumber - 1, c: 6 } });

        // Set column widths
        ws['!cols'] = [
            { wch: 8 },  // No.
            { wch: 30 }, // Unit (Asset Name)
            { wch: 20 }, // Category (Risk Name)
            { wch: 12 }, // Piping
            { wch: 12 }, // Piping %
            { wch: 12 }, // Equipment
            { wch: 12 }  // Equipment %
        ];

        // Create workbook and add worksheet
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'Report 2-1');

        // Generate and download file
        XLSX.writeFile(wb, `report_2_1_${new Date().toISOString().slice(0, 10)}.xlsx`);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50" onClick={onClose}>
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-[95vw] w-full mx-4 max-h-[90vh] overflow-hidden" onClick={(e) => e.stopPropagation()}>
                {/* Modal Header */}
                <div className="flex items-center justify-between p-5 border-b border-gray-200 dark:border-gray-700">
                    <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
                        {reportTitle || 'Report 2-1'}
                    </h3>
                    <button
                        onClick={onClose}
                        className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
                    >
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                {/* Modal Body */}
                <div className="p-5 overflow-auto max-h-[calc(90vh-140px)]">
                    {loading ? (
                        <div className="flex items-center justify-center py-12">
                            <div className="text-center">
                                <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
                                <p className="mt-4 text-gray-600 dark:text-gray-400">Loading report...</p>
                            </div>
                        </div>
                    ) : data.length === 0 ? (
                        <div className="flex items-center justify-center py-12">
                            <p className="text-gray-500 dark:text-gray-400">No data available</p>
                        </div>
                    ) : (
                        <div className="overflow-x-auto">
                            <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                                <thead className="bg-gray-50 dark:bg-gray-900">
                                    <tr>
                                        <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">No.</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Unit</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Category</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Piping</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Piping %</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Equipment</th>
                                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">Equipment %</th>
                                    </tr>
                                </thead>
                                <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                                    {data.map((row, index) => {
                                        // Check if this is the first row or if the ASSET_NAME is different from the previous row
                                        const showUnitAndNumber = index === 0 || data[index - 1].ASSET_NAME !== row.ASSET_NAME;
                                        const rowNumber = showUnitAndNumber ? (data.slice(0, index).filter((r, i) => i === 0 || data[i - 1].ASSET_NAME !== r.ASSET_NAME).length + 1) : null;

                                        return (
                                            <tr key={index} className="hover:bg-gray-50 dark:hover:bg-gray-700">
                                                <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100">
                                                    {showUnitAndNumber ? rowNumber : ''}
                                                </td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                    {showUnitAndNumber ? (row.ASSET_NAME || '-') : ''}
                                                </td>
                                                <td
                                                    className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100"
                                                    style={{
                                                        backgroundColor: row.RISK_COLOR
                                                            ? (row.RISK_COLOR.startsWith('#') ? row.RISK_COLOR : `#${row.RISK_COLOR}`)
                                                            : 'transparent'
                                                    }}
                                                >
                                                    {row.RISK_NAME || '-'}
                                                </td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.PIPING || '-'}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                    {row.PIPING_PCT != null && Number(row.PIPING_PCT) !== 0 ? Number(row.PIPING_PCT).toFixed(2) : ''}
                                                </td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">{row.EQUIPMENT || '-'}</td>
                                                <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                                    {row.EQUIPMENT_PCT != null && Number(row.EQUIPMENT_PCT) !== 0 ? Number(row.EQUIPMENT_PCT).toFixed(2) : ''}
                                                </td>
                                            </tr>
                                        );
                                    })}
                                    {/* Total Row */}
                                    <tr className="bg-gray-100 dark:bg-gray-700 font-bold">
                                        <td className="px-4 py-3 text-sm text-center text-gray-900 dark:text-gray-100"></td>
                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100"></td>
                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">TOTAL</td>
                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                            {data.reduce((sum, row) => sum + (Number(row.PIPING) || 0), 0)}
                                        </td>
                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                            {(() => {
                                                const total = data.reduce((sum, row) => sum + (Number(row.PIPING_PCT) || 0), 0);
                                                return total !== 0 ? total.toFixed(2) : '';
                                            })()}
                                        </td>
                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                            {data.reduce((sum, row) => sum + (Number(row.EQUIPMENT) || 0), 0)}
                                        </td>
                                        <td className="px-4 py-3 text-sm text-gray-900 dark:text-gray-100">
                                            {(() => {
                                                const total = data.reduce((sum, row) => sum + (Number(row.EQUIPMENT_PCT) || 0), 0);
                                                return total !== 0 ? total.toFixed(2) : '';
                                            })()}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>

                {/* Modal Footer */}
                <div className="flex items-center justify-end gap-3 p-5 border-t border-gray-200 dark:border-gray-700">
                    <button
                        onClick={handleExportToExcel}
                        className="btn btn-primary"
                        disabled={loading || data.length === 0}
                    >
                        Save
                    </button>
                    <button
                        onClick={onClose}
                        className="btn btn-outline-danger"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
};

export default Report21;
