// Category structures for CIG (CIV tables) and CRI (CRV tables)

export interface CategoryStructure {
    id: string;
    name: string;
    table: string;
}

export const cigStructure: CategoryStructure[] = [
    { id: 'acceptance-criteria', name: 'Acceptance Criteria', table: 'CIG_ACCEPTANCE_CRITERIA2_' },
    { id: 'aqueous-corrosion', name: 'Aqueous Corrosion', table: 'CIG_AQUEOUS_CORROSION' },
    { id: 'atmospheric-corrosion', name: 'Atmospheric Corrosion', table: 'CIG_ATMOSPHERIC_CORROSIO' },
    { id: 'business-information', name: 'Business Information', table: 'CIG_BUSSINESS_INFORMATIO' },
    { id: 'category-information', name: 'Category Information', table: 'CIG_CATEGORY_INFORMATION' },
    { id: 'co2-local-corrosion', name: 'CO2 Local Corrosion', table: 'CIG_CO2_LOCAL_CORROSION' },
    { id: 'co2-uniform-corrosion', name: 'CO2 Uniform Corrosion', table: 'CIG_CO2_UNIFORM_CORROSIO' },
    { id: 'cof-calculation', name: 'CoF Calculation', table: 'CIG_COF_CALCULATION' },
    { id: 'cof-calculation-dnv', name: 'CoF Calculation DNV', table: 'CIG_COF_CALCULATION_DNV' },
    { id: 'cof-calculation-level3', name: 'CoF Calculation Level 3', table: 'CIG_COF_CALCULATION_LEVE' },
    { id: 'cof-economic-dnv', name: 'CoF Economic DNV', table: 'CIG_COF_ECONOMIC_DNV' },
    { id: 'cof-environmental-dnv', name: 'CoF Environmental DNV', table: 'CIG_COF_ENVIRONMENTAL_DN' },
    { id: 'cof-parameter-dnv', name: 'CoF Parameter DNV', table: 'CIG_COF_PARAMETER_DNV' },
    { id: 'cof-safety-dnv', name: 'CoF Safety DNV', table: 'CIG_COF_SAFETY_DNV' },
    { id: 'complexity-of-fabricator', name: 'Complexity of Fabricator', table: 'CIG_COMPLEXITY_OF_FABRIC' },
    { id: 'complexity-of-fabricator2', name: 'Complexity of Fabricator 2', table: 'CIG_COMPLEXITY_OF_FABRIC2_' },
    { id: 'condition-affective-rate', name: 'Condition Affective Rate', table: 'CIG_CONDITION_AFFECTIVE' },
    { id: 'cui', name: 'CUI', table: 'CIG_CUI' },
    { id: 'cui-for-carbon-and-low', name: 'CUI For Carbon and Low', table: 'CIG_CUI_FOR_CARBON_AND_L' },
    { id: 'damage-mechanism', name: 'Damage Mechanism', table: 'CIG_DAMAGE_MECHANISM' },
    { id: 'damage-mechanism-2', name: 'Damage Mechanism 2', table: 'CIG_DAMAGE_MECHANISM_2' },
    { id: 'data-damage-mechanism', name: 'Data Damage Mechanism', table: 'CIG_DATA_DAMAGE_MECHANIS' },
    { id: 'data-of-technical-mode', name: 'Data of Technical Mode', table: 'CIG_DATA_OF_TECHNICAL_MO' },
    { id: 'degradation-mechanism', name: 'Degradation Mechanism', table: 'CIG_DEGRADATION_MECHANIS' },
    { id: 'dimension-information', name: 'Dimension Information', table: 'CIG_DIMENSION_INFORMATIO' },
    { id: 'economic-information', name: 'Economic Information', table: 'CIG_ECONOMIC_INFORMATION' },
    { id: 'environmental-cof-resume', name: 'Environmental CoF Resume', table: 'CIG_ENVIROMENTAL_COF_RES' },
    { id: 'environment-load-cond', name: 'Environment Load Cond', table: 'CIG_ENVIRONMENT_LOAD_CON' },
    { id: 'erosion', name: 'Erosion', table: 'CIG_EROSION' },
    { id: 'escc-stable', name: 'ESCC Stable', table: 'CIG_ESCC_STABLE' },
    { id: 'escc-unstable', name: 'ESCC Unstable', table: 'CIG_ESCC_UNSTABLE' },
    { id: 'fatigue', name: 'Fatigue', table: 'CIG_FATIGUE' },
    { id: 'fatigue-data', name: 'Fatigue Data', table: 'CIG_FATIGUE_DATA' },
    { id: 'flammable-area-resume', name: 'Flammable Area Resume', table: 'CIG_FLAMMABLE_AREA_RESUM' },
    { id: 'fluid-composition-dnv', name: 'Fluid Composition DNV', table: 'CIG_FLUID_COMPOSITION_DN' },
    { id: 'fluid-dnv', name: 'Fluid DNV', table: 'CIG_FLUID_DNV' },
    { id: 'h2s-cracking-stable', name: 'H2S Cracking Stable', table: 'CIG_H2S_CRACKING_STABLE' },
    { id: 'h2s-cracking-unstable', name: 'H2S Cracking Unstable', table: 'CIG_H2S_CRACKING_UNSTABL' },
    { id: 'heading', name: 'Heading', table: 'CIG_HEADING' },
    { id: 'heading-dnv', name: 'Heading DNV', table: 'CIG_HEADING_DNV' },
    { id: 'insignificant', name: 'Insignificant', table: 'CIG_INSIGNIFICANT' },
    { id: 'inspection-history', name: 'Inspection History', table: 'CIG_INSPECTION_HISTORY' },
    { id: 'inspection-history-dnv', name: 'Inspection History DNV', table: 'CIG_INSPECTION_HISTORY_D' },
    { id: 'inspection-judgement', name: 'Inspection Judgement', table: 'CIG_INSPECTION_JUDGEMENT' },
    { id: 'inspection-plan', name: 'Inspection Plan', table: 'CIG_INSPECTION_PLAN' },
    { id: 'inspection-plan-descript', name: 'Inspection Plan Descript', table: 'CIG_INSPECTION_PLAN_DESC' },
    { id: 'inspection-plan-dnv', name: 'Inspection Plan DNV', table: 'CIG_INSPECTION_PLAN_DNV' },
    { id: 'inspection-plan-no-insp', name: 'Inspection Plan No Insp', table: 'CIG_INSPECTION_PLAN_NO_I' },
    { id: 'inspection-plan-paramet', name: 'Inspection Plan Paramet', table: 'CIG_INSPECTION_PLAN_PARA' },
    { id: 'inspection-plan-suggest', name: 'Inspection Plan Suggest', table: 'CIG_INSPECTION_PLAN_SUGG' },
    { id: 'inspection-plan-suggest2', name: 'Inspection Plan Suggest 2', table: 'CIG_INSPECTION_PLAN_SUGG2_' },
    { id: 'inspection-plan-suggest3', name: 'Inspection Plan Suggest 3', table: 'CIG_INSPECTION_PLAN_SUGG3_' },
    { id: 'inspection-plan-suggest4', name: 'Inspection Plan Suggest 4', table: 'CIG_INSPECTION_PLAN_SUGG4_' },
    { id: 'installation-fabrication', name: 'Installation & Fabrication', table: 'CIG_INSTALLATION___FABRI' },
    { id: 'large-hole-size', name: 'Large Hole Size', table: 'CIG_LARGE_HOLE_SIZE' },
    { id: 'maintenance-history', name: 'Maintenance History', table: 'CIG_MAINTENANCE_HISTORY' },
    { id: 'maintenance-history2', name: 'Maintenance History 2', table: 'CIG_MAINTENANCE_HISTORY2_' },
    { id: 'material', name: 'Material', table: 'CIG_MATERIAL' },
    { id: 'material-and-coating', name: 'Material and Coating', table: 'CIG_MATERIAL_AND_COATING' },
    { id: 'mechanical-information', name: 'Mechanical Information', table: 'CIG_MECHANICAL_INFORMATI' },
    { id: 'medium-hole-size', name: 'Medium Hole Size', table: 'CIG_MEDIUM_HOLE_SIZE' },
    { id: 'mic', name: 'MIC', table: 'CIG_MIC' },
    { id: 'mitigation-system', name: 'Mitigation System', table: 'CIG_MITIGATION_SYSTEM' },
    { id: 'no-of-shutdown-per', name: 'No. of Shutdown per', table: 'CIG_NO__OF_SHUTDOWN_PER_' },
    { id: 'norsok-corrosion-rate', name: 'NORSOK Corrosion Rate', table: 'CIG_NORSOK_CORROSION_RAT' },
    { id: 'operating-condition', name: 'Operating Condition', table: 'CIG_OPERATING_CONDITION' },
    { id: 'other-information', name: 'Other Information', table: 'CIG_OTHER_INFORMATION' },
    { id: 'particle-parameter-dnv', name: 'Particle Parameter DNV', table: 'CIG_PARTICLE_PARAMETER_D' },
    { id: 'platform-information', name: 'Platform Information', table: 'CIG_PLATFORM_INFORMATION' },
    { id: 'pof-api-level-3-with', name: 'PoF API Level 3 with', table: 'CIG_POF_API_LEVEL_3_WITH' },
    { id: 'pof-api-level-3-with2', name: 'PoF API Level 3 with 2', table: 'CIG_POF_API_LEVEL_3_WITH2_' },
    { id: 'pof-calculation-dnv', name: 'PoF Calculation DNV', table: 'CIG_POF_CALCULATION_DNV' },
    { id: 'pof-dnv', name: 'PoF DNV', table: 'CIG_POF_DNV' },
    { id: 'probability-of-failure', name: 'Probability of Failure', table: 'CIG_PROBABILITY_OF_FAILU' },
    { id: 'process-data-dnv', name: 'Process Data DNV', table: 'CIG_PROCESS_DATA_DNV' },
    { id: 'process-information', name: 'Process Information', table: 'CIG_PROCESS_INFORMATION' },
    { id: 'risk-calculation-dnv', name: 'Risk Calculation DNV', table: 'CIG_RISK_CALCULATION_DNV' },
    { id: 'risk-s-02172006022639000', name: 'Risk S 02172006022639000', table: 'CIG_RISK_S_02172006022639000' },
    { id: 'risk-s-02172006022706000', name: 'Risk S 02172006022706000', table: 'CIG_RISK_S_02172006022706000' },
    { id: 'risk-status', name: 'Risk Status', table: 'CIG_RISK_STATUS' },
    { id: 'risk-summary-api-level', name: 'Risk Summary API Level', table: 'CIG_RISK_SUMMARY_API_LEV' },
    { id: 'risk-summary-api-level2', name: 'Risk Summary API Level 2', table: 'CIG_RISK_SUMMARY_API_LEV2_' },
    { id: 'risk-summary-dnv', name: 'Risk Summary DNV', table: 'CIG_RISK_SUMMARY_DNV' },
    { id: 'rupture-hole-size', name: 'Rupture Hole Size', table: 'CIG_RUPTURE_HOLE_SIZE' },
    { id: 'rbi-data', name: 'RBI Data', table: 'CIG_RBI_DATA' },
    { id: 'safety-system-information', name: 'Safety System Information', table: 'CIG_SAFETY_SYSTEM_INFORM' },
    { id: 'sap-property', name: 'SAP Property', table: 'CIG_SAP_PROPERTY' },
    { id: 'sap-property-20150507', name: 'SAP Property 20150507', table: 'CIG_SAP_PROPERTY_20150507' },
    { id: 'screening-damage-mechanism', name: 'Screening Damage Mechanism', table: 'CIG_SCREENING_DAMAGE_MEC' },
    { id: 'screening-parameter', name: 'Screening Parameter', table: 'CIG_SCREENING_PARAMETER' },
    { id: 'semi-quantitative-check', name: 'Semi Quantitative Check', table: 'CIG_SEMI_QUANTITATIVE_CH' },
    { id: 'small-hole-size', name: 'Small Hole Size', table: 'CIG_SMALL_HOLE_SIZE' },
    { id: 'sour-water-corrosion', name: 'Sour Water Corrosion', table: 'CIG_SOUR_WATER_CORROSION' },
    { id: 'ssc-susceptibility', name: 'SSC Susceptibility', table: 'CIG_SSC_SUSCEPTIBILITY' },
    { id: 'stability-rangking', name: 'Stability Rangking', table: 'CIG_STABILITY_RANGKING' },
    { id: 'statutory-certificate', name: 'Statutory Certificate', table: 'CIG_STATUTORY_CERTIFICAT' },
    { id: 'system-information-dnv', name: 'System Information DNV', table: 'CIG_SYSTEM_INFORMATION_D' },
    { id: 'tableku', name: 'Tableku', table: 'CIG_TABLEKU' },
    { id: 'technical-mode-module', name: 'Technical Mode Module', table: 'CIG_TECHNICAL_MODE_MODUL' },
    { id: 'test-test', name: 'Test Test', table: 'CIG_TEST_TEST' },
    { id: 'thickness', name: 'Thickness', table: 'CIG_THICKNESS' },
    { id: 'tmsf', name: 'TMSF', table: 'CIG_TMSF' },
    { id: 'tmsf-screening', name: 'TMSF Screening', table: 'CIG_TMSF_SCREENING' },
    { id: 'toxic-area-resume', name: 'Toxic Area Resume', table: 'CIG_TOXIC_AREA_RESUME' },
    { id: 'toxic-area-resume-dnv', name: 'Toxic Area Resume DNV', table: 'CIG_TOXIC_AREA_RESUME_DN' },
    { id: 'toxic-area-resume-dnv', name: 'Toxic Area Resume DNV', table: 'CIG_TOXIC_AREA_RESUME_DN' },
    { id: 'uniform-corrosion', name: 'Uniform Corrosion', table: 'CIG_UNIFORM_CORROSION' },
    { id: 'universal-information', name: 'Universal Information', table: 'CIG_UNIVERSAL_INFORMATIO' },
    { id: 'unknown', name: 'Unknown', table: 'CIG_UNKNOWN' },
];

export const criStructure: CategoryStructure[] = [
    { id: 'cri-amine-corrosion', name: 'Amine Corrosion', table: 'CRI_AMINE_CORROSION_RE2_' },
    { id: 'cri-api-copi-level-2', name: 'API COPI Level 2', table: 'CRI_API_COPI_LEVEL_2' },
    { id: 'cri-api-copi-level-3', name: 'API COPI Level 3', table: 'CRI_API_COPI_LEVEL3' },
    { id: 'cri-api581-l1', name: 'API581 L1', table: 'CRI_API581_L12_' },
    { id: 'cri-api581-l2', name: 'API581 L2', table: 'CRI_API581_L22_' },
    { id: 'cri-api-581-qualitative', name: 'API 581 Qualitative', table: 'CRI_API_581_QUALITATIVE' },
    { id: 'cri-consequence-of-failure-2', name: 'Consequence of Failure 2', table: 'CRI_CONSEQUENCE_OF_FAU2_' },
    { id: 'cri-piping-and-static-equipment', name: 'Piping and Static Equipment', table: 'CRI_PIPING_AND_STATICQ2_' },
    { id: 'cri-safety-relief-valves', name: 'Safety Relief Valves', table: 'CRI_SAFETY_RELIEF_VALVES' },
    { id: 'cri-asset-damage', name: 'Asset Damage', table: 'CRI_ASSET_DAMAGE' },
    { id: 'cri-af2', name: 'AF2', table: 'CRI_AF2_' },
    { id: 'cri-basic-release-rate', name: 'Basic Release Rate', table: 'CRI_BASIC_RELEASE_RATE' },
    { id: 'cri-bottom-plate-risk', name: 'Bottom Plate Risk', table: 'CRI_BOTTOM_PLATE_RISK' },
    { id: 'cri-brittle-fracture-tmsf', name: 'Brittle Fracture TMSF', table: 'CRI_BRITTLE_FACTURE_TF2_' },
    { id: 'cri-brittle-fracture', name: 'Brittle Fracture', table: 'CRI_BRITTLE_FRACTURE' },
    { id: 'cri-business-interruption-2', name: 'Business Interruption 2', table: 'CRI_BUSINESS_INTERRUPTIO2_' },
    { id: 'cri-business-interruption', name: 'Business Interruption', table: 'CRI_BUSINESS_INTERRUPTIO' },
    { id: 'cri-bussiness-interuption', name: 'Bussiness Interuption', table: 'CRI_BUSSINESS_INTERUPTIO' },
    { id: 'cri-calculated-rate', name: 'Calculated Rate', table: 'CRI_CALCULATED_RATE' },
    { id: 'cri-calculation', name: 'Calculation', table: 'CRI_CALCULATION' },
    { id: 'cri-calculation-2', name: 'Calculation 2', table: 'CRI_CALCULATION2_' },
    { id: 'cri-calculation-3', name: 'Calculation 3', table: 'CRI_CALCULATION3_' },
    { id: 'cri-calculation-4', name: 'Calculation 4', table: 'CRI_CALCULATION4_' },
    { id: 'cri-calculation-5', name: 'Calculation 5', table: 'CRI_CALCULATION5_' },
    { id: 'cri-calculation-6', name: 'Calculation 6', table: 'CRI_CALCULATION6_' },
    { id: 'cri-calculation-7', name: 'Calculation 7', table: 'CRI_CALCULATION7_' },
    { id: 'cri-calculation-8', name: 'Calculation 8', table: 'CRI_CALCULATION8_' },
    { id: 'cri-cate-2', name: 'CATE 2', table: 'CRI_CATE_2' },
    { id: 'cri-cf', name: 'CF', table: 'CRI_CF' },
    { id: 'cri-combined-tmsf', name: 'Combined TMSF', table: 'CRI_COMBINED_TMSF' },
    { id: 'cri-commercial-impact', name: 'Commercial Impact', table: 'CRI_COMMERCIAL_IMPACT2_' },
    { id: 'cri-ccf2', name: 'CCF2', table: 'CRI_CCF2_' },
    { id: 'cri-confidence-rating', name: 'Confidence Rating', table: 'CRI_CONFIDENCE_RATING2_' },
    { id: 'cri-consequence', name: 'Consequence', table: 'CRI_CONSEQUENCE' },
    { id: 'cri-consequence-category', name: 'Consequence Category', table: 'CRI_CONSEQUENCE_CATEGORY' },
    { id: 'cri-consequence-factor-2', name: 'Consequence Factor 2', table: 'CRI_CONSEQUENCE_FACTO_2_' },
    { id: 'cri-consequence-factor-5', name: 'Consequence Factor 5', table: 'CRI_CONSEQUENCE_FACTO_5_' },
    { id: 'cri-consequence-factor-4', name: 'Consequence Factor 4', table: 'CRI_CONSEQUENCE_FACTO_4_' },
    { id: 'cri-consequence-factor-9', name: 'Consequence Factor 9', table: 'CRI_CONSEQUENCE_FACTO_9_' },
    { id: 'cri-consequence-factor-a', name: 'Consequence Factor A', table: 'CRI_CONSEQUENCE_FACTO_A_' },
    { id: 'cri-consequence-factor', name: 'Consequence Factor', table: 'CRI_CONSEQUENCE_FACTOR__' },
    { id: 'cri-consequence-factor-8', name: 'Consequence Factor 8', table: 'CRI_CONSEQUENCE_FACTO_8_' },
    { id: 'cri-consequence-factor-3', name: 'Consequence Factor 3', table: 'CRI_CONSEQUENCE_FACTO_3_' },
    { id: 'cri-consequence-factor-6', name: 'Consequence Factor 6', table: 'CRI_CONSEQUENCE_FACTO_6_' },
    { id: 'cri-consequence-factor-main', name: 'Consequence Factor Main', table: 'CRI_CONSEQUENCE_FACTOR' },
    { id: 'cri-consequence-of-failure', name: 'Consequence of Failure', table: 'CRI_CONSEQUENCE_OF_FAILU' },
    { id: 'cri-consequence-of-failure-2', name: 'Consequence of Failure 2', table: 'CRI_CONSEQUENCE_OF_FAILU2_' },
    { id: 'cri-consequence-of-failure-3', name: 'Consequence of Failure 3', table: 'CRI_CONSEQUENCE_OF_FAILU3_' },
    { id: 'cri-consequence-of-failure-5', name: 'Consequence of Failure 5', table: 'CRI_CONSEQUENCE_OF_FAILU5_' },
    { id: 'cri-consequence-of-failure-4', name: 'Consequence of Failure 4', table: 'CRI_CONSEQUENCE_OF_FAILU4_' },
    { id: 'cri-consequence-rating-a', name: 'Consequence Rating A', table: 'CRI_CONSEQUENCE_RATIN_A_' },
    { id: 'cri-consequence-rating-3', name: 'Consequence Rating 3', table: 'CRI_CONSEQUENCE_RATIN_3_' },
    { id: 'cri-consequence-rating-6', name: 'Consequence Rating 6', table: 'CRI_CONSEQUENCE_RATIN_6_' },
    { id: 'cri-consequence-rating-2', name: 'Consequence Rating 2', table: 'CRI_CONSEQUENCE_RATIN_2_' },
    { id: 'cri-consequence-rating-5', name: 'Consequence Rating 5', table: 'CRI_CONSEQUENCE_RATIN_5_' },
    { id: 'cri-consequence-rating-8', name: 'Consequence Rating 8', table: 'CRI_CONSEQUENCE_RATIN_8_' },
    { id: 'cri-consequence-rating', name: 'Consequence Rating', table: 'CRI_CONSEQUENCE_RATING__' },
    { id: 'cri-consequence-rating-4', name: 'Consequence Rating 4', table: 'CRI_CONSEQUENCE_RATIN_4_' },
    { id: 'cri-consequence-rating-7', name: 'Consequence Rating 7', table: 'CRI_CONSEQUENCE_RATIN_7_' },
    { id: 'cri-consequence-rating-f4', name: 'Consequence Rating F4', table: 'CRI_CONSEQUENCE_RATINF4_' },
    { id: 'cri-consequence-rating-f2', name: 'Consequence Rating F2', table: 'CRI_CONSEQUENCE_RATINF2_' },
    { id: 'cri-consequence-rating-f', name: 'Consequence Rating F', table: 'CRI_CONSEQUENCE_RATING_F' },
    { id: 'cri-corrosion-rate', name: 'Corrosion Rate', table: 'CRI_CORROSION_RATE2_' },
    { id: 'cri-corrosion-type', name: 'Corrosion Type', table: 'CRI_CORROSION_TYPE2_' },
    { id: 'cri-crf', name: 'CRF', table: 'CRI_CRF' },
    { id: 'cri-crfh2', name: 'CRFH2', table: 'CRI_CRFH2_' },
    { id: 'cri-criticality', name: 'Criticality', table: 'CRI_CRITICALITY' },
    { id: 'cri-criticality-value', name: 'Criticality Value', table: 'CRI_CRITICALITY_VALUE2_' },
    { id: 'cri-damage-consequence', name: 'Damage Consequence', table: 'CRI_DAMAGE_CONSEQUENC2_' },
    { id: 'cri-damage-consequence-f', name: 'Damage Consequence F', table: 'CRI_DAMAGE_CONSEQUENCE_F' },
    { id: 'cri-df2', name: 'DF2', table: 'CRI_DF2_' },
    { id: 'cri-deadleg-factor', name: 'Deadleg Factor', table: 'CRI_DEADLEG_FACTOR' },
    { id: 'cri-detection-and-isolation', name: 'Detection and Isolation', table: 'CRI_DETECTION_AND_ISOLAT' },
    { id: 'cri-release-phase-calculation', name: 'Release Phase Calculation', table: 'CRI_RELEASE_PHASE_CALL2_' },
    { id: 'cri-dif2', name: 'DIF2', table: 'CRI_DIF2_' },
    { id: 'cri-dnv-detail-assessment', name: 'DNV Detail Assessment', table: 'CRI_DNV_DETAIL_ASSESSMEN' },
    { id: 'cri-dnv-detail-assessment-2', name: 'DNV Detail Assessment 2', table: 'CRI_DNV_DETAIL_ASSESSMEN2_' },
    { id: 'cri-dnv-screening', name: 'DNV Screening', table: 'CRI_DNV_SCREENING' },
    { id: 'cri-economic-category', name: 'Economic Category', table: 'CRI_ECONOMIC_CATEGORY' },
    { id: 'cri-economic-consequence', name: 'Economic Consequence', table: 'CRI_ECONOMIC_CONSEQUENCE' },
    { id: 'cri-economic-consequence-2', name: 'Economic Consequence 2', table: 'CRI_ECONOMIC_CONSEQUENCE2_' },
    { id: 'cri-economic-consequence-3', name: 'Economic Consequence 3', table: 'CRI_ECONOMIC_CONSEQUENCE3_' },
    { id: 'cri-economic-cost', name: 'Economic Cost', table: 'CRI_ECONOMIC_COST' },
    { id: 'cri-eemua-tanks', name: 'EEMUA Tanks', table: 'CRI_EEMUA_TANKS2_' },
    { id: 'cri-environment-category', name: 'Environment Category', table: 'CRI_ENVIRONMENT_CATEGORY' },
    { id: 'cri-environment-consequence', name: 'Environment Consequence', table: 'CRI_ENVIRONMENT_CONSEQUE' },
    { id: 'cri-environmental-consequence', name: 'Environmental Consequence', table: 'CRI_ENVIRONMENTAL_CONSEQ' },
    { id: 'cri-environmental-consequence-2', name: 'Environmental Consequence 2', table: 'CRI_ENVIRONMENTAL_CONSEQ2_' },
    { id: 'cri-environmental-cost', name: 'Environmental Cost', table: 'CRI_ENVIRONMENTAL_COST' },
    { id: 'cri-environmental-impact', name: 'Environmental Impact', table: 'CRI_ENVIRONMENTAL_IMPT2_' },
    { id: 'cri-equipment-lining', name: 'Equipment Lining', table: 'CRI_EQUIPMENT_LINING' },
    { id: 'cri-equipment-linings-tmsf', name: 'Equipment Linings TMSF', table: 'CRI_EQUIPMENT_LININGSM2_' },
    { id: 'cri-equipment-modification', name: 'Equipment Modification', table: 'CRI_EQUIPMENT_MODIFICATI' },
    { id: 'cri-damage-modes', name: 'Damage Modes', table: 'CRI_DAMAGE_MODES2_' },
    { id: 'cri-database', name: 'Database', table: 'CRI_DATABASE' },
    { id: 'cri-external-category', name: 'External Category', table: 'CRI_EXTERNAL_CATEGORY' },
    { id: 'cri-external-corrosion-3', name: 'External Corrosion 3', table: 'CRI_EXTERNAL_CORROSIO3_' },
    { id: 'cri-external-corrosion-2', name: 'External Corrosion 2', table: 'CRI_EXTERNAL_CORROSIO2_' },
    { id: 'cri-external-corrosion', name: 'External Corrosion', table: 'CRI_EXTERNAL_CORROSION' },
    { id: 'cri-external-corrosion-4', name: 'External Corrosion 4', table: 'CRI_EXTERNAL_CORROSIO4_' },
    { id: 'cri-external-corrosion-5', name: 'External Corrosion 5', table: 'CRI_EXTERNAL_CORROSIO5_' },
    { id: 'cri-external-damage', name: 'External Damage', table: 'CRI_EXTERNAL_DAMAGE' },
    { id: 'cri-external-damage-tmsf', name: 'External Damage TMSF', table: 'CRI_EXTERNAL_DAMAGE_TF2_' },
    { id: 'cri-external-degradation', name: 'External Degradation', table: 'CRI_EXTERNAL_DEGRADATION' },
    { id: 'cri-external-probability', name: 'External Probability', table: 'CRI_EXTERNAL_PROBABILITY' },
    { id: 'cri-factors-influencing', name: 'Factors Influencing', table: 'CRI_FACTORS_INFLUENCING_' },
    { id: 'cri-failure-history', name: 'Failure History', table: 'CRI_FAILURE_HISTORY' },
    { id: 'cri-failure-history-category', name: 'Failure History Category', table: 'CRI_FAILURE_HISTORY_CATE' },
    { id: 'cri-fatigue', name: 'Fatigue', table: 'CRI_FATIGUE' },
    { id: 'cri-fatigue-and-overstress', name: 'Fatigue and Overstress', table: 'CRI_FATIGUE_AND_OVERSTRE' },
    { id: 'cri-fatigue-and-overstress-2', name: 'Fatigue and Overstress 2', table: 'CRI_FATIGUE_AND_OVERSE2_' },
    { id: 'cri-fatigue-and-overstress-3', name: 'Fatigue and Overstress 3', table: 'CRI_FATIGUE_AND_OVERSE3_' },
    { id: 'cri-fatigue-and-overstress-4', name: 'Fatigue and Overstress 4', table: 'CRI_FATIGUE_AND_OVERSE4_' },
    { id: 'cri-fatigue-and-overstress-5', name: 'Fatigue and Overstress 5', table: 'CRI_FATIGUE_AND_OVERSE5_' },
    { id: 'cri-fatigue-category', name: 'Fatigue Category', table: 'CRI_FATIGUE_CATEGORY' },
    { id: 'cri-fatigue-probability', name: 'Fatigue Probability', table: 'CRI_FATIGUE_PROBABILITY' },
    { id: 'cri-features-influencing', name: 'Features Influencing', table: 'CRI_FEATURES_INFLUENCG2_' },
    { id: 'cri-financial-consequence', name: 'Financial Consequence', table: 'CRI_FINANCIAL_CONSEQUENC' },
    { id: 'cri-flammable-consequence-2', name: 'Flammable Consequence 2', table: 'CRI_FLAMMABLE_CONSEQUENC2_' },
    { id: 'cri-flammable-consequence-4', name: 'Flammable Consequence 4', table: 'CRI_FLAMMABLE_CONSEQUENC4_' },
    { id: 'cri-flammable-consequence', name: 'Flammable Consequence', table: 'CRI_FLAMMABLE_CONSEQUENC' },
    { id: 'cri-flammable-consequence-3', name: 'Flammable Consequence 3', table: 'CRI_FLAMMABLE_CONSEQUENC3_' },
    { id: 'cri-furnace-tube', name: 'Furnace Tube', table: 'CRI_FURNACE_TUBE' },
    { id: 'cri-furnace-tube-tmsf', name: 'Furnace Tube TMSF', table: 'CRI_FURNACE_TUBE_TMSF2_' },
    { id: 'cri-gas-release-rate', name: 'Gas Release Rate', table: 'CRI_GAS_RELEASE_RATE2_' },
    { id: 'cri-generic-failure-frequency', name: 'Generic Failure Frequency', table: 'CRI_GENERIC_FAILURE_FREQ' },
    { id: 'cri-hcl-corrosion-rate', name: 'HCL Corrosion Rate', table: 'CRI_HCL_CORROSION_RAT2_' },
    { id: 'cri-health-consequence', name: 'Health Consequence', table: 'CRI_HEALTH_CONSEQUENC2_' },
    { id: 'cri-health-consequence-f', name: 'Health Consequence F', table: 'CRI_HEALTH_CONSEQUENCE_F' },
    { id: 'cri-htha-tmsf', name: 'HTHA TMSF', table: 'CRI_HTHA_TMSF2_' },
    { id: 'cri-ht-h2s-corrosion', name: 'HT H2S Corrosion', table: 'CRI_HT_H2S_CORROSION_T2_' },
    { id: 'cri-ht-sulfidic-acid', name: 'HT Sulfidic Acid', table: 'CRI_HT_SULFIDIC_ACID_T2_' },
    { id: 'cri-htha', name: 'HTHA', table: 'CRI_HTHA' },
    { id: 'cri-impact-damage-5', name: 'Impact Damage 5', table: 'CRI_IMPACT_DAMAGE5_' },
    { id: 'cri-impact-damage-2', name: 'Impact Damage 2', table: 'CRI_IMPACT_DAMAGE2_' },
    { id: 'cri-impact-damage-3', name: 'Impact Damage 3', table: 'CRI_IMPACT_DAMAGE3_' },
    { id: 'cri-impact-damage', name: 'Impact Damage', table: 'CRI_IMPACT_DAMAGE' },
    { id: 'cri-impact-damage-4', name: 'Impact Damage 4', table: 'CRI_IMPACT_DAMAGE4_' },
    { id: 'cri-injection-point-factor', name: 'Injection Point Factor', table: 'CRI_INJECTION_POINT_FACT' },
    { id: 'cri-insignificant', name: 'Insignificant', table: 'CRI_INSIGNIFICANT' },
    { id: 'cri-inspection', name: 'Inspection', table: 'CRI_INSPECTION' },
    { id: 'cri-inspection-category', name: 'Inspection Category', table: 'CRI_INSPECTION_CATEGORY' },
    { id: 'cri-if', name: 'IF', table: 'CRI_IF' },
    { id: 'cri-inspection-plan-dnv', name: 'Inspection Plan DNV', table: 'CRI_INSPECTION_PLAN_DNV' },
    { id: 'cri-internal-category', name: 'Internal Category', table: 'CRI_INTERNAL_CATEGORY' },
    { id: 'cri-internal-corrosion', name: 'Internal Corrosion', table: 'CRI_INTERNAL_CORROSION' },
    { id: 'cri-internal-corrosion-2', name: 'Internal Corrosion 2', table: 'CRI_INTERNAL_CORROSIO2_' },
    { id: 'cri-internal-corrosion-3', name: 'Internal Corrosion 3', table: 'CRI_INTERNAL_CORROSIO3_' },
    { id: 'cri-internal-corrosion-4', name: 'Internal Corrosion 4', table: 'CRI_INTERNAL_CORROSIO4_' },
    { id: 'cri-internal-corrosion-5', name: 'Internal Corrosion 5', table: 'CRI_INTERNAL_CORROSIO5_' },
    { id: 'cri-internal-degradation', name: 'Internal Degradation', table: 'CRI_INTERNAL_DEGRADATION' },
    { id: 'cri-internal-probability', name: 'Internal Probability', table: 'CRI_INTERNAL_PROBABILITY' },
    { id: 'cri-interval-factor', name: 'Interval Factor', table: 'CRI_INTERVAL_FACTOR' },
    { id: 'cri-large-release', name: 'Large Release', table: 'CRI_LARGE_RELEASE' },
    { id: 'cri-launchers-receivers', name: 'Launchers Receivers', table: 'CRI_LAUNCHERS__RECEIVERS' },
    { id: 'cri-likelihood-analysis', name: 'Likelihood Analysis', table: 'CRI_LIKELIHOOD_ANALYSIS' },
    { id: 'cri-likelihood-category', name: 'Likelihood Category', table: 'CRI_LIKELIHOOD_CATEGORY' },
    { id: 'cri-part-b-likelihood-c', name: 'Part B Likelihood C', table: 'CRI_PART_B__LIKELIHOOD_C' },
    { id: 'cri-likelihood-category-2', name: 'Likelihood Category 2', table: 'CRI_LIKELIHOOD_CATEGO2_' },
    { id: 'cri-likelihood-factor', name: 'Likelihood Factor', table: 'CRI_LIKELIHOOD_FACTOR' },
    { id: 'cri-likelihood-factor-2', name: 'Likelihood Factor 2', table: 'CRI_LIKELIHOOD_FACTOR2_' },
    { id: 'cri-likelihood-of-failure', name: 'Likelihood of Failure', table: 'CRI_LIKELIHOOD_OF_FAIR2_' },
    { id: 'cri-liquid-release-rate', name: 'Liquid Release Rate', table: 'CRI_LIQUID_RELEASE_RA2_' },
    { id: 'cri-location-of-tank-farm', name: 'Location of Tank Farm', table: 'CRI_LOCATION_OF_TANK_FAR' },
    { id: 'cri-major-failure-risk', name: 'Major Failure Risk', table: 'CRI_MAJOR_FAILURE_RISK' },
    { id: 'cri-marine-growth', name: 'Marine Growth', table: 'CRI_MARINE_GROWTH3_' },
    { id: 'cri-maximum-inspection-interval', name: 'Maximum Inspection Interval', table: 'CRI_MAXIMUM_INSPECTIOI2_' },
    { id: 'cri-mdf', name: 'MDF', table: 'CRI_MDF' },
    { id: 'cri-mechanical-fatigue', name: 'Mechanical Fatigue', table: 'CRI_MECHANICAL_FATIGUE' },
    { id: 'cri-mechanical-fatigue-tmsf', name: 'Mechanical Fatigue TMSF', table: 'CRI_MECHANICAL_FATIGUP2_' },
    { id: 'cri-medium-release', name: 'Medium Release', table: 'CRI_MEDIUM_RELEASE' },
    { id: 'cri-minor-failure-risk', name: 'Minor Failure Risk', table: 'CRI_MINOR_FAILURE_RISK' },
    { id: 'cri-on-line-monitoring-factor', name: 'On Line Monitoring Factor', table: 'CRI_ON_LINE_MONITORING_F' },
    { id: 'cri-onshore-consequence', name: 'Onshore Consequence', table: 'CRI_ONSHORE_CONSEQUEN2_' },
    { id: 'cri-onshore-likelihood', name: 'Onshore Likelihood', table: 'CRI_ONSHORE_LIKELIHOOD' },
    { id: 'cri-onshore-pipeline', name: 'Onshore Pipeline', table: 'CRI_ONSHORE_PIPELINE' },
    { id: 'cri-overdesign-factor', name: 'Overdesign Factor', table: 'CRI_OVERDESIGN_FACTOR2_' },
    { id: 'cri-part-a-release-rate', name: 'Part A Release Rate', table: 'CRI_PART_A__RELEASE_RE2_' },
    { id: 'cri-part-c-flammable-consequence', name: 'Part C Flammable Consequence', table: 'CRI_PART_C__FLAMABLE_CON' },
    { id: 'cri-part-d-consequence', name: 'Part D Consequence', table: 'CRI_PART_D__CONSEQUEN_2_' },
    { id: 'cri-person-loss-life', name: 'Person Loss Life', table: 'CRI_PERSON_LOSS_LIFE' },
    { id: 'cri-personnel-injury-cost', name: 'Personnel Injury Cost', table: 'CRI_PERSONNEL_INJURY_COS' },
    { id: 'cri-pipeline', name: 'Pipeline', table: 'CRI_PIPELINE3_' },
    { id: 'cri-plant-qual-rbi', name: 'Plant Qual RBI', table: 'CRI_PLANT_QUAL_RBI2_' },
    { id: 'cri-pof-value', name: 'PoF Value', table: 'CRI_POF_VALUE' },
    { id: 'cri-pof-h2s-cracking-uns', name: 'PoF H2S Cracking UNS', table: 'CRI_POF_H2S_CRACKING_UNS' },
    { id: 'cri-polarid-factor-2', name: 'Polarid Factor 2', table: 'CRI_POLARID_FACTOR2' },
    { id: 'cri-ppf2', name: 'PPF2', table: 'CRI_PPF2_' },
    { id: 'cri-prf2', name: 'PRF2', table: 'CRI_PRF2_' },
    { id: 'cri-probability', name: 'Probability', table: 'CRI_PROBABILITY' },
    { id: 'cri-probability-factor-4', name: 'Probability Factor 4', table: 'CRI_PROBABILITY_FACTOF4_' },
    { id: 'cri-probability-factor-3', name: 'Probability Factor 3', table: 'CRI_PROBABILITY_FACTOF3_' },
    { id: 'cri-probability-factor-f', name: 'Probability Factor F', table: 'CRI_PROBABILITY_FACTOR_F' },
    { id: 'cri-probability-of-failure', name: 'Probability of Failure', table: 'CRI_PROBABILITY_OF_FAILU' },
    { id: 'cri-probability-of-failure-2', name: 'Probability of Failure 2', table: 'CRI_PROBABILITY_OF_FAILU2_' },
    { id: 'cri-probability-of-failure-4', name: 'Probability of Failure 4', table: 'CRI_PROBABILITY_OF_FAILU4_' },
    { id: 'cri-probability-of-failure-3', name: 'Probability of Failure 3', table: 'CRI_PROBABILITY_OF_FAILU3_' },
    { id: 'cri-probability-rating-f4', name: 'Probability Rating F4', table: 'CRI_PROBABILITY_RATINF4_' },
    { id: 'cri-probability-rating-f2', name: 'Probability Rating F2', table: 'CRI_PROBABILITY_RATINF2_' },
    { id: 'cri-probability-rating-f', name: 'Probability Rating F', table: 'CRI_PROBABILITY_RATING_F' },
    { id: 'cri-pf2', name: 'PF2', table: 'CRI_PF2_' },
    { id: 'cri-production-value', name: 'Production Value', table: 'CRI_PRODUCTION_VALUE2_' },
    { id: 'cri-q4-leakage-factor', name: 'Q4 Leakage Factor', table: 'CRI_Q4___LEAKAGE_FACT2_' },
    { id: 'cri-quantitative-prodt', name: 'Quantitative PRODT', table: 'CRI_QUANTITATIVE_PRODT2_' },
    { id: 'cri-qf2', name: 'QF2', table: 'CRI_QF2_' },
    { id: 'cri-calculation-detail', name: 'Calculation Detail', table: 'CRI_CALCULATION_DETAI2_' },
    { id: 'cri-release-category', name: 'Release Category', table: 'CRI_RELEASE_CATEGORY' },
    { id: 'cri-release-type-calculation', name: 'Release Type Calculation', table: 'CRI_RELEASE_TYPE_CALCA2_' },
    { id: 'cri-remnant-life', name: 'Remnant Life', table: 'CRI_REMNANT_LIFE2_' },
    { id: 'cri-hole-sizes', name: 'Hole Sizes', table: 'CRI_HOLE_SIZES' },
    { id: 'cri-risk-2', name: 'Risk 2', table: 'CRI_RISK2_' },
    { id: 'cri-risk', name: 'Risk', table: 'CRI_RISK' },
    { id: 'cri-risk-4', name: 'Risk 4', table: 'CRI_RISK4_' },
    { id: 'cri-risk-5', name: 'Risk 5', table: 'CRI_RISK5_' },
    { id: 'cri-risk-3', name: 'Risk 3', table: 'CRI_RISK3_' },
    { id: 'cri-risk-6', name: 'Risk 6', table: 'CRI_RISK6_' },
    { id: 'cri-risk-7', name: 'Risk 7', table: 'CRI_RISK7_' },
    { id: 'cri-risk-9', name: 'Risk 9', table: 'CRI_RISK9_' },
    { id: 'cri-risk-10', name: 'Risk 10', table: 'CRI_RISK10_' },
    { id: 'cri-risk-11', name: 'Risk 11', table: 'CRI_RISK11_' },
    { id: 'cri-risk-12', name: 'Risk 12', table: 'CRI_RISK12_' },
    { id: 'cri-risk-13', name: 'Risk 13', table: 'CRI_RISK13_' },
    { id: 'cri-risk-14', name: 'Risk 14', table: 'CRI_RISK14_' },
    { id: 'cri-risk-15', name: 'Risk 15', table: 'CRI_RISK15_' },
    { id: 'cri-roof-plate-risk', name: 'Roof Plate Risk', table: 'CRI_ROOF_PLATE_RISK' },
    { id: 'cri-roof-supporting-structure', name: 'Roof Supporting Structure', table: 'CRI_ROOF_SUPPORTING_STRU' },
    { id: 'cri-rupture-release', name: 'Rupture Release', table: 'CRI_RUPTURE_RELEASE' },
    { id: 'cri-safety-and-environmental', name: 'Safety and Environmental', table: 'CRI_SAFETY_AND_ENVIROE2_' },
    { id: 'cri-safety-aspects-f2', name: 'Safety Aspects F2', table: 'CRI_SAFETY_ASPECTS___F2_' },
    { id: 'cri-safety-aspects-onsite', name: 'Safety Aspects Onsite', table: 'CRI_SAFETY_ASPECTS___ONS' },
    { id: 'cri-safety-category', name: 'Safety Category', table: 'CRI_SAFETY_CATEGORY' },
    { id: 'cri-safety-consequence', name: 'Safety Consequence', table: 'CRI_SAFETY_CONSEQUENCE' },
    { id: 'cri-safety-consequence-2', name: 'Safety Consequence 2', table: 'CRI_SAFETY_CONSEQUENCE2_' },
    { id: 'cri-safety-consequence-c', name: 'Safety Consequence C', table: 'CRI_SAFETY_CONSEQUENCE_C' },
    { id: 'cri-scc', name: 'SCC', table: 'CRI_SCC' },
    { id: 'cri-shell-plate-risk', name: 'Shell Plate Risk', table: 'CRI_SHELL_PLATE_RISK' },
    { id: 'cri-shore-zone-consequence', name: 'Shore Zone Consequence', table: 'CRI_SHORE_ZONE_CONSEQN2_' },
    { id: 'cri-shore-zone', name: 'Shore Zone', table: 'CRI_SHORE_ZONE' },
    { id: 'cri-shore-zone-likelihood', name: 'Shore Zone Likelihood', table: 'CRI_SHORE_ZONE_LIKELIHOO' },
    { id: 'cri-small-release', name: 'Small Release', table: 'CRI_SMALL_RELEASE' },
    { id: 'cri-sf2', name: 'SF2', table: 'CRI_SF2_' },
    { id: 'cri-release-rate-calculation', name: 'Release Rate Calculation', table: 'CRI_RELEASE_RATE_CALCA2_' },
    { id: 'cri-scc-tmsf', name: 'SCC TMSF', table: 'CRI_SCC_TMSF2_' },
    { id: 'cri-subsea-pipeline-consequence', name: 'Subsea Pipeline Consequence', table: 'CRI_SUBSEA_PIPELINE_CS2_' },
    { id: 'cri-subsea-pipeline', name: 'Subsea Pipeline', table: 'CRI_SUBSEA_PIPELINE' },
    { id: 'cri-subsea-pipeline-likelihood', name: 'Subsea Pipeline Likelihood', table: 'CRI_SUBSEA_PIPELINE_LIKE' },
    { id: 'cri-subsea-riser-consequence', name: 'Subsea Riser Consequence', table: 'CRI_SUBSEA_RISER_CONSU2_' },
    { id: 'cri-subsea-riser', name: 'Subsea Riser', table: 'CRI_SUBSEA_RISER' },
    { id: 'cri-subsea-riser-likelihood', name: 'Subsea Riser Likelihood', table: 'CRI_SUBSEA_RISER_LIKEH2_' },
    { id: 'cri-tmsf', name: 'TMSF', table: 'CRI_TMSF' },
    { id: 'cri-test', name: 'Test', table: 'CRI_TEST' },
    { id: 'cri-thinning', name: 'Thinning', table: 'CRI_THINNING' },
    { id: 'cri-thinning-tmsf', name: 'Thinning TMSF', table: 'CRI_THINNING_TMSF2_' },
    { id: 'cri-topsides-consequence', name: 'Topsides Consequence', table: 'CRI_TOPSIDES_CONSEQUEE2_' },
    { id: 'cri-topsides-likelihood', name: 'Topsides Likelihood', table: 'CRI_TOPSIDES_LIKELIHO2_' },
    { id: 'cri-topsides-likelihood-3', name: 'Topsides Likelihood 3', table: 'CRI_TOPSIDES_LIKELIHO3_' },
    { id: 'cri-topsides-likelihood-4', name: 'Topsides Likelihood 4', table: 'CRI_TOPSIDES_LIKELIHO4_' },
    { id: 'cri-topsides-likelihood-full', name: 'Topsides Likelihood Full', table: 'CRI_TOPSIDES_LIKELIHOOD' },
    { id: 'cri-topsides-riser', name: 'Topsides Riser', table: 'CRI_TOPSIDES_RISER' },
    { id: 'cri-toxic-consequence', name: 'Toxic Consequence', table: 'CRI_TOXIC_CONSEQUENCE' },
    { id: 'cri-toxic-consequence-2', name: 'Toxic Consequence 2', table: 'CRI_TOXIC_CONSEQUENCE2_' },
    { id: 'cri-toxic-consequence-category', name: 'Toxic Consequence Category', table: 'CRI_TOXIC_CONSEQUENCE_CA' },
    { id: 'cri-toxic-consequence-category-2', name: 'Toxic Consequence Category 2', table: 'CRI_TOXIC_CONSEQUENCE_CA2_' },
    { id: 'cri-tqf', name: 'TQF', table: 'CRI_TQF' },
    { id: 'cri-unknown', name: 'Unknown', table: 'CRI_UNKNOWN' },
    { id: 'cri-wall-loss-fraction', name: 'Wall Loss Fraction', table: 'CRI_WALL_LOSS_FRACTIOA2_' },
    { id: 'cri-wet-h2s-cracking', name: 'Wet H2S Cracking', table: 'CRI_WET_H2S_CRACKING' },
];

// RISK categories - RBI tables
export const riskStructure: CategoryStructure[] = [
    { id: 'risk-afm-deg-mech-cat', name: 'AFM Deg Mech Cat', table: 'rbi_afm_deg_mech_cat' },
    { id: 'risk-assessment-data', name: 'Assessment Data', table: 'RBI_ASSESSMENT_DATA' },
    { id: 'risk-assessment-data-id', name: 'Assessment Data ID', table: 'RBI_ASSESSMENT_DATA_ID' },
    { id: 'risk-asset', name: 'Asset', table: 'rbi_asset' },
    { id: 'risk-asset-06012014', name: 'Asset 06012014', table: 'rbi_asset_06012014' },
    { id: 'risk-asset-06022006-1844', name: 'Asset 06022006 1844', table: 'rbi_asset_06022006_1844' },
    { id: 'risk-asset-230805', name: 'Asset 230805', table: 'rbi_asset_230805' },
    { id: 'risk-asset-25012006', name: 'Asset 25012006', table: 'rbi_asset_25012006' },
    { id: 'risk-asset-26012005-sore', name: 'Asset 26012005 SORE', table: 'rbi_asset_26012005_SORE' },
    { id: 'risk-asset-old', name: 'Asset Old', table: 'rbi_asset_old' },
    { id: 'risk-asset-old2', name: 'Asset Old 2', table: 'rbi_asset_old2' },
    { id: 'risk-asset-original', name: 'Asset Original', table: 'rbi_asset_original' },
    { id: 'risk-case', name: 'Case', table: 'rbi_case' },
    { id: 'risk-certificate-expiry', name: 'Certificate Expiry', table: 'rbi_certificate_expiry' },
    { id: 'risk-comp-type', name: 'Component Type', table: 'rbi_comp_type' },
    { id: 'risk-component', name: 'Component', table: 'rbi_component' },
    { id: 'risk-cost-for-equipment', name: 'Cost for Equipment', table: 'rbi_cost_for_equipment' },
    { id: 'risk-cost-for-equipment-dnv', name: 'Cost for Equipment DNV', table: 'rbi_cost_for_equipment_dnv' },
    { id: 'risk-cost-for-piping', name: 'Cost for Piping', table: 'rbi_cost_for_piping' },
    { id: 'risk-cost-for-piping-dnv', name: 'Cost for Piping DNV', table: 'rbi_cost_for_piping_dnv' },
    { id: 'risk-damage-mech-config', name: 'Damage Mech Config', table: 'rbi_damage_mech_config' },
    { id: 'risk-damage-mech-function', name: 'Damage Mech Function', table: 'RBI_DAMAGE_MECH_FUNCTION' },
    { id: 'risk-damage-mech-table', name: 'Damage Mech Table', table: 'RBI_DAMAGE_MECH_TABLE' },
    { id: 'risk-damage-mechanism-table', name: 'Damage Mechanism Table', table: 'RBI_Damage_Mechanism_Table' },
    { id: 'risk-def-type', name: 'Def Type', table: 'rbi_def_type' },
    { id: 'risk-default-font', name: 'Default Font', table: 'RBI_Default_Font' },
    { id: 'risk-factor', name: 'Factor', table: 'RBI_Factor' },
    { id: 'risk-factor-old', name: 'Factor Old', table: 'rbi_factor_old' },
    { id: 'risk-field-def', name: 'Field Def', table: 'rbi_field_def' },
    { id: 'risk-field-type', name: 'Field Type', table: 'rbi_field_type' },
    { id: 'risk-fn-category', name: 'Fn Category', table: 'rbi_fn_category' },
    { id: 'risk-fn-constant', name: 'Fn Constant', table: 'rbi_fn_constant' },
    { id: 'risk-fn-definition', name: 'Fn Definition', table: 'rbi_fn_definition' },
    { id: 'risk-fn-input', name: 'Fn Input', table: 'RBI_Fn_Input' },
    { id: 'risk-fn-inspection', name: 'Fn Inspection', table: 'RBI_Fn_Inspection' },
    { id: 'risk-fn-inspection-desc', name: 'Fn Inspection Desc', table: 'RBI_Fn_Inspection_Desc' },
    { id: 'risk-fn-inspection-risk', name: 'Fn Inspection Risk', table: 'RBI_Fn_Inspection_Risk' },
    { id: 'risk-fn-inspection-risk-id', name: 'Fn Inspection Risk ID', table: 'RBI_Fn_Inspection_Risk_ID' },
    { id: 'risk-fn-inspection-technique', name: 'Fn Inspection Technique', table: 'RBI_Fn_Inspection_Technique' },
    { id: 'risk-fn-inspection-technique-desc', name: 'Fn Inspection Technique Desc', table: 'RBI_Fn_Inspection_Technique_Desc' },
    { id: 'risk-fn-inverse', name: 'Fn Inverse', table: 'rbi_fn_inverse' },
    { id: 'risk-fn-parameter', name: 'Fn Parameter', table: 'rbi_fn_parameter' },
    { id: 'risk-fn-result-type', name: 'Fn Result Type', table: 'rbi_fn_result_type' },
    { id: 'risk-fn-risk', name: 'Fn Risk', table: 'rbi_fn_risk' },
    { id: 'risk-grid-style', name: 'Grid Style', table: 'rbi_grid_style' },
    { id: 'risk-group', name: 'Group', table: 'rbi_group' },
    { id: 'risk-history', name: 'History', table: 'RBI_History' },
    { id: 'risk-image-test', name: 'Image Test', table: 'RBI_Image_Test' },
    { id: 'risk-info-def', name: 'Info Def', table: 'rbi_info_def' },
    { id: 'risk-ins-task', name: 'Ins Task', table: 'rbi_ins_task' },
    { id: 'risk-insp-task2', name: 'Insp Task 2', table: 'rbi_insp_task2' },
    { id: 'risk-inspection-all', name: 'Inspection All', table: 'RBI_INSPECTION_ALL' },
    { id: 'risk-inspection-all-dnv', name: 'Inspection All DNV', table: 'RBI_INSPECTION_ALL_DNV' },
    { id: 'risk-inspection-data', name: 'Inspection Data', table: 'RBI_INSPECTION_DATA' },
    { id: 'risk-inspection-data-id', name: 'Inspection Data ID', table: 'RBI_INSPECTION_DATA_ID' },
    { id: 'risk-inspection-matrix', name: 'Inspection Matrix', table: 'RBI_Inspection_Matrix' },
    { id: 'risk-inspection-plan', name: 'Inspection Plan', table: 'rbi_inspection_plan' },
    { id: 'risk-inspection-plan-2015', name: 'Inspection Plan 2015', table: 'rbi_inspection_plan_2015' },
    { id: 'risk-inspection-plan-20150609', name: 'Inspection Plan 20150609', table: 'rbi_inspection_plan_20150609' },
    { id: 'risk-inspection-plan-dnv-description', name: 'Inspection Plan DNV Description', table: 'rbi_inspection_plan_dnv_description' },
    { id: 'risk-inspection-plan-dnv-table', name: 'Inspection Plan DNV Table', table: 'rbi_inspection_plan_dnv_table' },
    { id: 'risk-inspection-plan-pmanda', name: 'Inspection Plan Pmanda', table: 'rbi_inspection_plan_pmanda' },
    { id: 'risk-inspection-plan-year-def', name: 'Inspection Plan Year Def', table: 'RBI_INSPECTION_PLAN_YEAR_DEF' },
    { id: 'risk-inspection-year', name: 'Inspection Year', table: 'RBI_INSPECTION_YEAR' },
    { id: 'risk-insulation', name: 'Insulation', table: 'rbi_insulation' },
    { id: 'risk-lookup-item', name: 'Lookup Item', table: 'rbi_lookup_item' },
    { id: 'risk-lookup-list', name: 'Lookup List', table: 'rbi_lookup_list' },
    { id: 'risk-material', name: 'Material', table: 'rbi_material' },
    { id: 'risk-matrix-cell', name: 'Matrix Cell', table: 'rbi_matrix_cell' },
    { id: 'risk-matrix-risk', name: 'Matrix Risk', table: 'rbi_matrix_risk' },
    { id: 'risk-matrix-type', name: 'Matrix Type', table: 'rbi_matrix_type' },
    { id: 'risk-model', name: 'Model', table: 'RBI_Model' },
    { id: 'risk-model-calc', name: 'Model Calc', table: 'rbi_model_calc' },
    { id: 'risk-model-calc-id', name: 'Model Calc ID', table: 'rbi_model_calc_id' },
    { id: 'risk-model-level', name: 'Model Level', table: 'RBI_Model_Level' },
    { id: 'risk-pfd', name: 'PFD', table: 'RBI_PFD' },
    { id: 'risk-repair', name: 'Repair', table: 'rbi_repair' },
    { id: 'risk-report', name: 'Report', table: 'rbi_report' },
    { id: 'risk-report-parameter', name: 'Report Parameter', table: 'rbi_report_parameter' },
    { id: 'risk-report-parameter-id', name: 'Report Parameter ID', table: 'rbi_report_parameter_id' },
    { id: 'risk-report-properties', name: 'Report Properties', table: 'rbi_report_properties' },
    { id: 'risk-rbi-risk', name: 'RBI Risk', table: 'rbi_risk' },
    { id: 'risk-rbi-risk-level', name: 'RBI Risk Level', table: 'rbi_risk_level' },
    { id: 'risk-risk-query', name: 'Risk Query', table: 'RBI_Risk_Query' },
    { id: 'risk-risk-summary', name: 'Risk Summary', table: 'rbi_risk_summary' },
    { id: 'risk-rpt-s-p-parameter', name: 'Rpt S P Parameter', table: 'rbi_rpt_s_p_parameter' },
    { id: 'risk-rpt-s-p-parameter-id', name: 'Rpt S P Parameter ID', table: 'rbi_rpt_s_p_parameter_id' },
    { id: 'risk-rpt-stored-procedure', name: 'Rpt Stored Procedure', table: 'rbi_rpt_stored_procedure' },
    { id: 'risk-table-def', name: 'Table Def', table: 'rbi_table_def' },
    { id: 'risk-table-sp', name: 'Table SP', table: 'RBI_Table_SP' },
    { id: 'risk-temp-ct-id', name: 'Temp CT ID', table: 'rbi_temp_CT_ID' },
    { id: 'risk-tmsf-damage', name: 'TMSF Damage', table: 'rbi_TMSF_Damage' },
    { id: 'risk-unit', name: 'Unit', table: 'rbi_unit' },
    { id: 'risk-user', name: 'User', table: 'rbi_user' },
    { id: 'risk-user-activity', name: 'User Activity', table: 'rbi_user_activity' },
    { id: 'risk-user-font', name: 'User Font', table: 'RBI_User_Font' },
    { id: 'risk-user-font-desc', name: 'User Font Desc', table: 'RBI_User_Font_Desc' },
    { id: 'risk-user-group', name: 'User Group', table: 'RBI_User_Group' },
    { id: 'risk-user-track', name: 'User Track', table: 'rbi_user_track' },
    { id: 'risk-variables-calc-desc', name: 'Variables Calc Desc', table: 'rbi_variables_calc_desc' },
    { id: 'risk-variables-calc-value', name: 'Variables Calc Value', table: 'rbi_variables_calc_value' },
    { id: 'risk-variables-desc', name: 'Variables Desc', table: 'rbi_variables_desc' },
    { id: 'risk-variables-general-desc', name: 'Variables General Desc', table: 'rbi_variables_general_desc' },
    { id: 'risk-variables-general-value', name: 'Variables General Value', table: 'rbi_variables_general_value' },
    { id: 'risk-variables-value', name: 'Variables Value', table: 'rbi_variables_value' },
    { id: 'risk-view-risk-query', name: 'View Risk Query', table: 'rbi_view_risk_query' },
    { id: 'risk-view-risk-query-exc', name: 'View Risk Query Exc', table: 'rbi_view_risk_query_exc' },
    { id: 'risk-work-pack', name: 'Work Pack', table: 'rbi_work_pack' },
];
